### ISSUE TITLE
Document the light client protocol and changes to the Raiden client/transport

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1]
## Description
We discussed the light client protocol in our kick-off workshop. The outcome should be documented.

## Acceptance criteria
- It is written down, what we have discussed
- There is an agreement between @hackaugusto and @andrevmatos 
- Changes needed for the Raiden client are specified
- People outside the team understand it

## Tasks
- [x] Write down the spec in Github
- [x] Add details and comments on https://github.com/raiden-network/raiden/issues/3254
- [x] Create issue for SecretReveal (Done: https://github.com/raiden-network/raiden/issues/3513)
- [x] Get feedback from @rakanalh and @LefterisJP 
- [x] Get priority on Delivered and SecreatReveal

## Story Points
3
