### ISSUE TITLE
Receiving transfers in the SDK

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1209]
## Description
Follow up to #1132 

Finalize receiving transfers in the SDK including
- [x] Single PR for receiving
- [x] Include CLI optimizations
- [ ] Tests
- [ ] Knowledge sharing
    - [ ] Code Review (explanation by André)
    - [x] Testing and reviewing the code (Thomas/Kelsos)
    - [ ] Going through the [Raiden Docs / protocol](https://raiden-network-specification.readthedocs.io/en/latest/mediated_transfer.html#mediated-transfer-happy-path-scenario
) together looking at the pictures (maybe enhanced by André)
- [x] Discussion of the approach with the Raiden Python Team
- [x] Pass CodeClimate
- [ ] Documentation
- [x] Manual testing

## Acceptance criteria
- We have got a feature flag (Disabled = default)
- In the dApp we have got an alert (Callback)
- We can use the CLI to test the receiving transfers
- The whole team understands the code
- The Raiden core team understands what we are doing

## Critical Issues
- https://github.com/raiden-network/raiden-contracts/issues/1370

## Tasks
- [ ]

**Comment by christianbrb** [comment]
Documentation: 
- https://raiden-network-specification.readthedocs.io/en/latest/mediated_transfer.html#mediated-transfer-happy-path-scenario

**Comment by christianbrb** [comment]
Review by the Raiden Python Team (@hackaugusto @Dominik1999)

Notes
- Code Walkthrough by @andrevmatos 
- Q & A:
    - Q: Processed still in the code A: Working with Processed and without
    - Q: Do refunds work? A: Not yet
- Remarks by @hackaugusto 
    -  Considering processing messages to the MS and PFS at once
         - HTTP is expensive
         - Collapsing balance proofs -> only sending the last one
    - Looking at the python code how sync issues have been solved (Race conditions MS/PFS <->client)

Supports:
- Restarts
- Capabilities
- Works without delivered

Not yet implemented:
- Refund (maybe it's going to be removed as it needs a lot of collateral)
- Monitoring Service
- The economic viability of on-chain secret registration
- Reroute
- Signature for RevealSecret
- Remove Delivered
- Mediation (one additional epic)

@Dominik1999 @hackaugusto @andrevmatos Let me know, if this is documented correctly. Thanks :)

CC @GataKamsky
