### ISSUE TITLE
Document how to update the testenv001 environment

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1316]
## User Story
As a developer I want to know the steps on how to update the test environment `testenv001`

## Acceptance criteria

* We should also think if it's possible to simplify it, e.g. not having to specify specific commits in the different repos but instead have testenv001 tags everywhere that we can move around

## Tasks
- [ ] Review integration steps https://github.com/raiden-network/light-client/tree/master/integration#updating-the-image
- [ ] Update the Raiden Hub -> Hub repo
- [ ] Update the Raiden Service Bundle -> RSB Rep -> check with @eorituz 
- [ ] Update smart contracts -> SDK

**Comment by kelsos** [comment]
On the simplification step, I am not sure if it would be easy to achieve it on the integration image part.

**Comment by nephix** [comment]
It was just an idea, not sure how viable it is :)
