### ISSUE TITLE
Download SDK via NPM

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#14]
## User Story
As Kelsos I want to download the SDK from NPM so that I can include in my JavaScript project.

## Acceptance criteria
- I can type 'npm install raiden-client' and the light client sdk gets installed
- After install, I am able to install it
- Only light client sdk gets installed (if possible)

## Tasks
- [ ] Configure npm account (Raiden network has got alread an organization)
- [ ] Choose a name (raiden.ts)
- [ ] Configure .npmrc 
- [ ] Package .json to publish

## Story Points

2

**Comment by andrevmatos** [comment]
Done: https://www.npmjs.com/package/raiden-ts
