### ISSUE TITLE
Create a pull request template for the Definition of Done

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1422]
## Description
Create a pull request template to check if a PR fulfills the Definition of Done.
- [x] Acceptance Criteria are met #1411 
- [x] dApp - PR has been manually tested #1406 
- [x] Test script is available #1406 

## Acceptance criteria
- 

## Tasks
- [ ]
