### ISSUE TITLE
Mainnet smoke testing

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1426]
## Description
Currently, we are testing on Goerli, which is a PoA chain. In addition, the python client is getting tested on Mainnet and they are experiencing some issues they haven't seen before on testnet.

To avoid this from happening for the Light Client we should run a mainnet smoketest to check,
- how long the blockchain transactions take
- what the blockchain transactions cost
- if we find any error or UX problem, we haven't seen on testnet

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by kelsos** [comment]
@christianbrb it's not only the PoA vs PoW but also mainnet has a lot of load and events, while Goerli doesn't have the same volume. Even if we were running on a PoW testnet we could not possibly simulate the mainnet conditions 100%.

**Comment by andrevmatos** [comment]
# Steps for mainnet testing

Testing a served dApp is simple, we just need to ensure the environment variables which override PFS and transport servers (to our `testenv001` environments) aren't set:

1. Ensure SDK and dApp dependencies are up-to-date
2. Update the `raiden-contracts` submodule to `v0.37.0` (Alderaan):
```sh
cd raiden-ts/raiden-contracts
git fetch --all -pt
git checkout v0.37.0
cd ..
```
2. Ensure SDK build is up-to-date:
```sh
npm run build
cd ..
```
3. Chose one of Alderaan transport servers from [here](https://github.com/raiden-network/raiden-service-bundle/blob/master/known_servers/known_servers.alderaan.yaml)
4. Serve `dApp` in a mode different than the testenv001 ones (`development`, `ghpages`, `raiden-package`), and set transport server:
```sh
cd raiden-dapp
export VUE_APP_TRANSPORT="https://<alderaan_matrix>"
npm run serve -- --mode mainnet
```
This will ensure the following environment variables are **not** set or changed by `vue serve`:
- VUE_APP_PFS: unset defaults to fetching from ServiceRegistry contract on mainnet
- VUE_APP_TRANSPORT: unset defaults to fetching from test yml, but we need to specify an Alderaan one (above)
- VUE_APP_HUB: hub is on old testenv001 and won't work on mainnet, so need to stay unset
- VUE_APP_ALLOW_MAINNET: unset or anything different from `false` won't disable mainnet

5. Access the dApp at `https://localhost:8080`
  - Be mindful that the generated Raiden account is specific to the address above, so you'd get a different one if running on a different port or trying to access an instance hosted on a diferent domain; keep that in mind before depositing anything on UDC or channels for Raiden account; nonetheless, it's fully recoverable (deterministically generated) from anywhere with the same main (Metamask) account, and not locked in your browser, storage or instance.
  - Be double careful to not clear or delete the state (`localStorage`). Back it up (download) after each session. State can only actively be lost (e.g. by cleaning browsing data). SDK tries its best to recover at any time, but full state reset can be considered undefined behavior and one could end up losing funds locked on some channel if resetting while there're non-settled channels.

**Comment by kelsos** [comment]
@andrevmatos, In general, it looks ok to me but this `mainnet` mode doesn't exist right? maybe we should include an example of `.env.mainnet.example` file and guide the people interested in using that on how to create the actual `.env.mainnet` configuration that will work with the `--mode mainnet`

**Comment by nephix** [comment]
Might be easier to provide testers with just a build that is already main net configured and that they can serve locally instead of providing them steps on how to fiddle around with our setup

**Comment by agatsoh** [comment]
- [ ]  Initialisation and token balance
- [ ]  Approving of  Deposit of service tokens in UDC
- [ ] Direct transfers
- [ ] One hop mediated transfers with python client(initiator light client)
One issue with this after one or two mediating transfer subsequent mediated transfers do not go through documented in this issue
https://github.com/raiden-network/light-client/issues/1831
- [ ] Withdraw(After withdraw light client gets Nonce out of sync exceptions while python client initiates mediated transfer to the light client(receiver) yet to open an issue after and test again )
- [ ] deposit
- [ ]  transferring tokens and eth from raiden account to main account and vice versa(one more test run required as tested long back)
- [ ] fees
- [ ] downloading logs
 
please feel to add items to the list

**Comment by christianbrb** [comment]
- Let's create individual issues for each test run and schedule them

Closing this one
