### ISSUE TITLE
Architecture of token transfers in sdk

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#143]
## Description

Before starting to implement the token transfers we should design the architecture

## Acceptance criteria
- Not mediating transfers
- No refunds off-chain
- Description how to create a balance proof
- Describe how to populate the pending locks merkle tree
- Description how a balance proof is signed
- The data model is modeled
- When and how to expire a lock
- Christian, Kelsos, and Stefan understand it
- Documentation is improved to enable other projects to develop a Raiden client
- Presented to core devs
- Just focus on the v0.4 contracts (Red Eyes)

## Tasks
- [x] Reading smart contracts specification v0.4 (@christianbrb and @kelsos)
- [ ] Update the Raiden specification @kelsos @Dominik1999 @christianbrb 
    - [x] How do we interact on it? Google Docs or PR?
- [ ] Create a data model @andrevmatos 
    - [ ] Channel state data model @andrevmatos 
    - [ ] How the state data is getting updated @andrevmatos 
- [ ] Write down the state and actions (state changes) @andrevmatos  

## Additional information
- [Raiden Messages Specification](https://raiden-network-specification.readthedocs.io/en/latest/messaging.html)
- ~~[Description of the Raiden State Machines](https://raiden-network.readthedocs.io/en/latest/state_machines.html)~~ outdated
- [Raiden Smart Contracts Specification](https://raiden-network-specification.readthedocs.io/en/latest/smart_contracts.html)
- [Raiden developer onboarding guide](https://raiden-network.readthedocs.io/en/latest/onboarding.html)
- [Raiden transfer directory](https://github.com/raiden-network/raiden/tree/master/raiden/transfer)
- [Picture regarding the message flow from the light client kick-off workshop](https://user-images.githubusercontent.com/35398162/58076303-29f3a180-7baa-11e9-9f30-3bda0336c960.png)

### 1. Send a Locked Transfer

[Data Structure](https://raiden-network-specification.readthedocs.io/en/latest/messaging.html#id3)
- [ ] What needs to be done to prepare the data?

["Invariant"](https://raiden-network-specification.readthedocs.io/en/latest/messaging.html#id2)
- [ ] Remove what is not needed, if we don't mediate a message

[Python Code](https://github.com/raiden-network/raiden/blob/38971b372dafb3205cbd3df8cfc3306922a55eac/raiden/messages.py#L1124)
- [ ] Document Methods

### 2. Receive a Secret Request

[Data Structure](https://raiden-network-specification.readthedocs.io/en/latest/messaging.html#id5)

["Invariant"](https://raiden-network-specification.readthedocs.io/en/latest/messaging.html#id4)

### 3. Send a ReveilSecret

[Data Structure](https://raiden-network-specification.readthedocs.io/en/latest/messaging.html#id6)

### 6. Send a LockExpired message
If the target does not request the secret

### A. Processed
All ?accepted? messages should be confirmed by a `Processed` message which echoes the orginal Message hash.
[Message Acknowledgement and Processing](https://raiden-network.readthedocs.io/en/latest/onboarding.html#messages-acknowledgment-and-processing)

### B. Delivered
The message used to inform the partner node that a message was received *and* persisted.
[Message Acknowledgement and Processing](https://raiden-network.readthedocs.io/en/latest/onboarding.html#messages-acknowledgment-and-processing)

## Data
- [Test data](https://github.com/raiden-network/raiden/tree/master/raiden/tests/unit/storage/migrations/data)

**Comment by christianbrb** [comment]
Comment from @hackaugusto 

Documenting what we discussed during the workshop [...]

For milestone 0 the light client will not handle receiving payments, only sending. We decided to not create a new protocol, but to use the existing protocol, there are some special cases for a few messages that are worth mentioning.

When a light client receives a `LockedTransfer` or a `RefundTransfer` message it must be *fakely* processes it, meaning it does not validate the messages but it does send a `Processed` message to the sender. Explanation:

- For a `LockedTransfer`: The Raiden network does not currently support capabilities, because of this there is no way to distinguish a light client from a full node, because of this a hub can't tell if the other end of a channel is a light client or not. Usually a light client will have only 1 channel open with a hub, as a consequence the hub will not try to send a transfer through the light client, however this cannot be enforced, in the exceptional case of a light client with more than 1 open channel, it's possible a hub may try forwarding a transfer through the light client. In this case the light client should respond the `LockedTransfer` with a `Processed` message, but **don't** forward the transfer. The rationale is that the hub's sender queue  has to be cleared, and because the light client does not forward the `LockedTransfer` nor send a `SecretRequest` eventually the lock will expire, and the transfer will **not** be made.
- For a `RefundTransfer`: It is possible  the hub can't forward the light client's transfer, in this case it will send a `RefundTransfer` back to the light client, this message too has to be cleared from the hub's queue by sending a `Processed` message back, but the secret **must not** be revealed. Eventually the lock will expire and the lock can be removed, so a payment will **not** be made to the initiator.

Because of the above, a light client may receive balance proofs from its hub, we have decided to **not** store these balance proofs, the reasoning is the light client will never effectively receive a payment, so all balance proofs *to the light client* will have a transferred amount of **zero**. For the purposes of settlement, using the latest valid balance proof with an empty merkle tree and a transferred amount of 0, or no balance proof at all, results in the same final balances. Since the hub cannot provide the balance proof on the light client behalf, and the light client is **not** using a monitoring service, the balance proof data will not required (The light client can close the channel with no data, and it does not need to call update).

**IMPORTANT**: The above has to be fixed once the light client starts to receive payments, and that can only be done once **monitoring services** are operational.
