### ISSUE TITLE
Metamask Error: dApp gives access denied error if Metamask account is still locked

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#147]
## Description

Not sure if the errors/exceptions are different or could be detected, but upon clicking `Connect`, if Metamask is still locked (no password was input on Metamask) it gives `access denied` right away.

## Tasks (suggested)
- [ ] Detect and inform user if the account is locked (instead of saying it was denied)
- [ ] Polls when it happens and then try to unlock the account
- [ ] Show proper error messages for both cases

**Comment by kelsos** [comment]
So this seems to be a bug on Metamask's latest update https://github.com/MetaMask/metamask-extension/issues/6618
I tried on firefox with 6.5.1 and I still get the login popup when calling `ethereum.enable` with metamask as the provider. On the other hand on Chrome with 6.5.2 I get the same behavior you described above.

**Comment by kelsos** [comment]
So technically the error message you get is the same in both cases.
There is no distinction between a locked provider and the user not approving the metamask connection. 

Both cases fail with the following error: 

```javascript
Error: unknown account #0 (operation="getAddress", version=4.0.27)
    at Object.throwError (errors.js?3e4e:76)
    at eval (json-rpc-provider.js?5f08:87)
```
The best I can do is change the message to something more generic like:

```
A valid account could not be detected. 
Please make sure that your provider is unlocked and accessible.
```
