### ISSUE TITLE
Transfer screen and history feedback

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1510]
## Description
Some feedback within the demo
- [x] If there is no transfer remove the "transfer history" label or add "0 transfers" below the label
- [x] Showing the tokens behind the number within the transfer history (#1493 fixed this)
- [x] Enter address or ENS name below the field is redundant and should not be shown if the field hasn't been touched
- [x] Left corner on transfer icon cut off
- [x] Date and time is 10px and should be 12px

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
Marking this as ready as those are just small improvements

**Comment by nephix** [comment]
> If there is no transfer remove the "transfer history" label or add "0 transfers" below the label

When I started to work on this, this was already checked so I didn't look into it. It seems like it's still not fixed though
