### ISSUE TITLE
Update to Alderaan

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1610]
## Description
Now that Alderaan is out it makes sense to update the test environment and integration image to Alderaan.

## Acceptance criteria
- 

## Tasks
- [x] New environment
- [x] Updating the contracts
- [x] Update references in the repo (URLs, env variables, etc.)
- [x] Update the integration image
- [x] Update Raiden Hub
- [x] Fix signature mismatches

**Comment by christianbrb** [comment]
Coordinate with @eorituz

**Comment by eorituz** [comment]
I'll setup testenv002 tomorrow and also push a new docker container.
I'll give you all the info tomorrow once it's done.

**Comment by eorituz** [comment]
Alright after talking to Christian and Kelsos we decided to go with an Alderaan compatible demo environment.
I set everything up using the following specs
|   |   |
|---|---|
| Matrix | `raidentransport.demo001.env.raiden.network` |
| Raiden version | [Alderaan](https://github.com/raiden-network/raiden/releases/tag/v1.0.0) - commit `0bb7220d6a7058c1fac2dc78ba0ccda8d81034d0` |
| PFS | `pfs.raidentransport.demo001.env.raiden.network`|
| RSB | Release [2020.05.0](https://github.com/raiden-network/raiden-service-bundle/tree/2020.05.0) |
| Docker | [`raidennetwork/raiden:demoenv001`](https://hub.docker.com/layers/raidennetwork/raiden/demoenv001/images/sha256-3ea2c9d1d838cd87b8e60690b50f12664e43062c6343e5d0df2df2c2536c26b7?context=repo) |

Please give the DNS entries some time to spread. As the time of writing the entry isn't propagated yet, so the PFS/MATRIX isn't reachable yet.

CC @kelsos @andrevmatos @taleldayekh @christianbrb @agatsoh
