### ISSUE TITLE
Upgrade to ethers v5

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#1707]
## Description
[Ethers v5](https://github.com/ethers-io/ethers.js/releases) is a big refactoring of the `ethers` web3 library, the core of our blockchain interaction. This major release changes a lot of utility functions and assumptions. Considering we rely quite deeply on some v4 implementation details, this should be a larger task, but the improvements, new features, stability and bugfixes it brings is worth it, so we should do this sooner than later, to avoid writing more code that will be needed to be refactored.

## Acceptance criteria
- We use ethers v5 on the whole codebase
- It works the same as before (no regressions)
- Events are reviewed in detail

see https://github.com/raiden-network/light-client/pull/2289#issuecomment-717609592 for details

## Tasks
- [x] Researching the steps needed for the upgrade @andrevmatos 
- [x] Splitting the issue into separate issues @andrevmatos 
- [x] sdk src imports (@andrevmatos)
- [x] sdk tests imports (@agatsoh, can you do it, please?)
    - [x] sdk mocks (@andrevmatos) 
- [x] dapp imports (@weilbith, can you do it, please?)
- [x] cli imports (@palango, can you do it, please?)
- [x] sdk tests fixes (@andrevmatos, after builds pass)
- [x] run the tests
- [x] test by hand

**Comment by andrevmatos** [comment]
[@typechain/ethers-v5@1.0.0](https://github.com/ethereum-ts/TypeChain/pull/252) is merged and released. We should do this soon, this is quite an important library for us to stay behind too long.

**Comment by christianbrb** [comment]
The migration guide: https://docs.ethers.io/v5/migration/ethers-v4/

**Comment by christianbrb** [comment]
Blocked by #2044
