### ISSUE TITLE
Adjust UDC deposit dialog for mainnet

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#1770]
## User Story
As Chris I want to acquire and deposit mainnet utility tokens in the UDC screen. Split from issue #587 

## Acceptance criteria
- Dialog should display standard input field for amount
- Deposit button should be disabled if the user has not purchased any utility tokens
- Dialog should provide a link to Uniswap with a predefined utility token amount of 10
- Dialog should display utility token amount that a user has purchased (transaction completed)
- Dialog should let the user select how many utility tokens to deposit and enable the deposit button

## Tasks
- [ ] Prepare mockup that everyone is aligned on and then vote on this again
- [ ] In-iteration design
- [ ] Make sure component is separated from the testnet one

**Comment by christianbrb** [comment]
After @taleldayekh's [comment](https://github.com/raiden-network/light-client/issues/587#issuecomment-648101164), I would add here
- The dialog should show a warning if the amount of available tokens is lower than the entered amount (see eg. transfer amount input field)

**Comment by kelsos** [comment]
@christianbrb the title seems wrong. The deposit should work fine in mainnet if you have RDN on your account. This is about improving and enhancing the existing dialog.

**Comment by christianbrb** [comment]
@kelsos I have updated the title.

Let's talk in detail within the planning :)

**Comment by taleldayekh** [comment]
@raiden-network/light-client 

![mainnet-deposit](https://user-images.githubusercontent.com/43838780/87922798-ca7a7580-ca7c-11ea-9ece-c8d6455da0d4.jpg)

**Comment by weilbith** [comment]
Overall I like the basic design. Simple and straight forward. 
So here are a few nitpicks:
  - The available balance could be better visible, as it is now "hidden" within the text.
  - On the first screen it is not too obvious that the user lacks in a positive balance to deposit.
  - What does this component take as default suggestion value? (looks you take it all)

**Comment by taleldayekh** [comment]
Thank you @weilbith

We can make the balance more prominent. Regarding the default suggestion, I would say we go with the entire purchased amount after a purchase has just been made, else just 0.

**Comment by taleldayekh** [comment]
![deposit](https://user-images.githubusercontent.com/43838780/87938390-cf4c2300-ca96-11ea-88cd-b8a5b8070827.jpg)

**Comment by christianbrb** [comment]
Deposit RDN -> Deposit to UDC
