### ISSUE TITLE
Smaller visual issues (maybe after Vue upgrade)

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1783]
## Description

- [x] 1. Address is black instead of white (I don't remember how it was before)

![grafik](https://user-images.githubusercontent.com/35398162/85522535-15cc7000-b606-11ea-982e-be6f09bf6242.png)

- [x] 2. Two lines instead of one on token amount display

![grafik](https://user-images.githubusercontent.com/35398162/85522857-78be0700-b606-11ea-8a31-fb073ef2ae88.png)

- [x] 3. Sent to and address are not horizontally aligned

![grafik](https://user-images.githubusercontent.com/35398162/85523466-4cef5100-b607-11ea-8e45-dead22f29d66.png)

- [x] 4. Net below Open Channel is cut (not fully visible)

![grafik](https://user-images.githubusercontent.com/35398162/85524780-c3408300-b608-11ea-83e9-2a177a8ca944.png)

## Acceptance criteria
- 

## Tasks
- [ ]
