### ISSUE TITLE
Define text for error messages and implement

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#181]
## Description
Define text for error messages and implement

## Acceptance criteria
- Error messages are gathered at one place
- Errors are reviewed
- Messages fit the space we have (it depends)
- Messages avoid tech jargon

## Tasks
- [x] Start searching for a known way for internationalization for Vue apps
- [x] "Translate" the errors
- [x] Proof check that error messages fit within the layout

## Supporting

See https://uxplanet.org/how-to-write-good-error-messages-858e4551cd4

**Comment by christianbrb** [comment]
Closed via #241
