### ISSUE TITLE
Notification when other party settled channel

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#1824]
## Description

When the other party of a channel has settled, the channel disappears from the channel list. Therefore he has to go to the token withdraw screen of his account to get the tokens back on his main account. This requires advanced knowledge of
the dApp.
A nice solution would be to get a notification of a settled channel. This notification allows then to get forwarded to the withdraw screen. Thereby this event gets not missed by the user and he gets pointed where to withdraw.

## Acceptance criteria
- user receives notification when other party has settled a channel
- notification somehow points the user to how claiming his tokens

## Tasks
- [ ] Need to have the snackbar pr closed before we start more work on notifications
- [ ] Expose event in the SDK
- [ ] In the notification, inform the user where on the account screen to get tokens back

**Comment by christianbrb** [comment]
@weilbith Thanks for raising the issue. This is very important for the user to trust the system (see https://github.com/raiden-network/light-client/issues/1757).
