### ISSUE TITLE
Move blockchain-interacting logic from Raiden class to state machine

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#1908]
## Description
Currently, there're some methods on the `Raiden` class (public interface of SDK) which, although not changing directly the state, interact with blockchain in a read-write manner and should be put in the state machine as their own epics instead, and through their own AsyncActionCreators

## Acceptance criteria
- No rw blockchain logic is present on Raiden

## Tasks
- [ ] `mint` becomes an AAC and epic (suggestion: on `channels/`)
- [ ] `depositToUDC` becomes an AAC and epic (suggestion: on `services/`)
- [ ] `transferOnchainBalance` becomes an AAC and epic (suggestion: on `channels/`)
- [ ] `transferOnchainTokens` becomes an AAC and epic (suggestion: on `channels/`)
