### ISSUE TITLE
Update developer documentation

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1947]
## Description
Within our retro, we have decided to update the developer documentation.

## Acceptance criteria
- The developer documentation should reflect the current codebase, architecture, and processes
- Adding what is missing
- Just check, what is currently written, but if it is up to date, don't change it

## Tasks
- [x] Update https://github.com/raiden-network/light-client/blob/master/raiden-ts/docs-source/SDK-Development.md
- [x] Review and update if necessary https://github.com/raiden-network/light-client/tree/master/raiden-cli
- [x] Review and update if necessary https://github.com/raiden-network/light-client/blob/master/raiden-ts/docs-source/installing-sdk.md
- [x] Review and update if necessary https://github.com/raiden-network/light-client/blob/master/raiden-ts/docs-source/installing-dapp.md

**Comment by weilbith** [comment]
The retro is suuuuuper long ago. Does anyone remember what we decided to update here? What would be the requirements for this issue? Not sure what to write here.
