### ISSUE TITLE
Update to the latest Raiden Python client release - v1.1.1

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1951]
## Description
There is a new Raiden Python client release (https://github.com/raiden-network/raiden/releases/tag/v1.1.1).
We need to update our infrastructure.

## Acceptance criteria
- 

## Tasks
- [ ] Update references in the repo (URLs, env variables, etc.)
- [ ] Update the integration image
- [ ] Update Raiden Hub

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by weilbith** [comment]
The PR to do the updates is merged. I'm just preparing the CHANGELOG and will open a PR for the version bump soon.

**Comment by weilbith** [comment]
New compatible version got released.
