### ISSUE TITLE
Basic development environment set-up

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2]
##  Description
The basic development environment is set up.

## Acceptance criteria
- Github is set up
- Basic CI to run the checks are working
- A POC test is implemented
- A basic readme is available
- Basic requirements are included
- The build is split up
- Prettier, ESlint, TypeScript, Web3, Webpack, Jest, Jasmin

## Tasks
- [x] Set up repository
- [x] Check with @karlb about mono repo built
- [x] Add license
- [x] Create readme
- [x] Requirements SDK
- [x] Vue set up
- [x] Copy CircleCI from WebUI and adjust
- [x] Define requirements for Wallet
- [x] Add dev. requirements

## Story Points
5
