### ISSUE TITLE
Update naming in dapp to match design naming

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#205]
## Description

Currently, a lot of pages in the dapp follow a different naming scheme than the ones in the proposed design. This can create a lot of confusion. We should follow the same naming scheme in both the design and code to avoid confusion.

@roy-castrillo We need to spend some time together for this to set a terminology that we both follow afterward.

## Acceptance criteria
-  Consistent naming of screens across design and implementation

## Tasks
- [x] Check for inconsistencies in the naming between design and implementation
- [x] Decide on naming
- [ ] Update naming on implementation
