### ISSUE TITLE
Run all the scenarios after IndexedDB refactoring

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2091]
## Description
To fully test the implementation of #2044 we should run all available scenarios manually.

## Acceptance criteria
- The process how to run scenarios is documented
- All scenarios have been executed by @agatsoh 

## Tasks
- [x] Write one task for each scenario to tick them off one by one
- [x] [bf1_basic_functionality](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/bf1_basic_functionality.yaml) @agatsoh 
- [x] [bf2_long_running](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/bf2_long_running.yaml) @andrevmatos 
- [x] [bf3_multi_directional_payment](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/bf3_multi_directional_payment.yaml) @andrevmatos 
- [x] [bf4_multi_payments_same_node](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/bf4_multi_payments_same_node.yaml) @andrevmatos 
- [x] [bf5_join_and_leave](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/bf5_join_and_leave.yaml) @andrevmatos 
- [x] [bf6_stress_hub_node](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/bf6_stress_hub_node.yaml) @andrevmatos  
- [x] [bf7_long_path](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/bf7_long_path.yaml) @andrevmatos 
- [x] [ms1_simple_monitoring](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/ms1_simple_monitoring.yaml) @agatsoh
- [x] [ms2_simple_monitoring](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/ms2_simple_monitoring.yaml) @agatsoh
- [x] [ms3_simple_monitoring](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/ms3_simple_monitoring.yaml) @andrevmatos 
- [x] [ms4_udc_too_low](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/ms4_udc_too_low.yaml) @agatsoh
- [x] [pfs1_get_a_simple_path](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/pfs1_get_a_simple_path.yaml) @agatsoh
- [x] [pfs2_simple_no_path](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/pfs2_simple_no_path.yaml) @taleldayekh 
- [x] [pfs3_multiple_paths](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/pfs3_multiple_paths.yaml) @agatsoh
- [x] [pfs4_use_best_path](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/pfs4_use_best_path.yaml) @agatsoh
- [x] [pfs5_too_low_capacity](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/pfs5_too_low_capacity.yaml) @agatsoh
- [x] [pfs6_simple_path_rewards](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/pfs6_simple_path_rewards.yaml) @agatsoh
- [x] [pfs7_multiple_payments](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/pfs7_multiple_payments.yaml) @agatsoh
- [x] [pfs8_mediator_goes_offline](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml) @agatsoh
- [x] [pfs9_partial_withdraw](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios/pfs9_partial_withdraw.yaml) @agatsoh

**Comment by christianbrb** [comment]
Pushing that to the current iteration to run them after a PR for #2044 has been submitted.

**Comment by agatsoh** [comment]
I ran the BF1 scenario on the scenario player by following instructions in this PR of Andre
https://github.com/raiden-network/light-client/pull/1954

Invariably I get this error
https://gist.github.com/agatsoh/fcbd43528eedc12b369a593780669017

**Comment by andrevmatos** [comment]
I've tried running some early scenarios on the PR. With it, I discovered an issue with the test environment, where PFSs are returning BigNumbers (> 2^53) as JSON numbers (where Raiden core returns such numbers encoded as strings). This gave us trouble since we removed lossless-json (#2072).
Also, SP is also passing numbers on amounts to the API, which also gives problems when these numbers are big.
I commited the fixes, and got BF4 and BF1 to pass. Only required change was the `raiden_version` on the scenarios pointing to the `raiden-cli/raiden` script.

**Comment by agatsoh** [comment]
I am trying to get bf1 running currently and  after that I will try all the others as well.

**Comment by taleldayekh** [comment]
pfs2 scenarios successful 👍

**Comment by andrevmatos** [comment]
I've reproduced @agatsoh's issue locally. I'm trying to debug it. Looks like webRTC native lib hits some sort of infinite loop internally upon getting connected on a machine/client which has many connections (so it shows more often on scenarios like BF1 & BF6), which makes CPUs go crazy. This doesn't seem something related to our code, profiling has shown only `(program)` stack element taking that much CPU, which is usually for native modules..
The worse about it is that it's hard to detect on our code, the `open` event go through, but no messages flow between clients.
Scenarios should run fine if one disable webRTC in config, but I'm looking on finding some fix or workaround sooner than later.
This doesn't seem to affect browsers, only cli with `node-webrtc` lib.

**Comment by christianbrb** [comment]
Running on https://github.com/raiden-network/light-client/tree/feature/to_device
0. Update dependencies
1. Build SDK
2. Build CLI
