### ISSUE TITLE
dApp: define global alignment grid for view components and header

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#2095]
## Description

At the moment does each view replicates the styling to have a padding and align everything left and right. The same goes for the header. This is quite cumbersome, duplicated code, new views are "hard" to add and changing the alignment increases linear in work according to the number of views and different headers. Also do special cases to treat the spacing differently not become highlighted in the code. Since all are using absolute numbers, it requires to open all component files and compare the values to see exceptions. Exceptions must be commented. Everything is hard to debug when the grid does not work.
Therefore this alignment/styling should be defined as high as possible in the component tree. Then all views and headers can simply take the full width and hight without caring for paddings etc.

There are two different obvious solutions. 

a)
Simply add a padding to the App component to create the space to all its child components.

_Pro_: 
- no child (view/route or header) can escape this boundary
- styling is clear and easy to understand (basically a single line of code)

_Contra:_
- eventual exceptions (Christian is picky) can't escape this setting
- fixed assumption that headers share the same background color like the view/route

b)
App component sets a padding to all it's first level child components.

_Pro:_
- children can escape this boundary and introduce exceptions that are cleary visible (code-wise) as such

_Contra:_
- weak restriction for children
- styling might not be obvious, because App component defines styling for its children

## Acceptance criteria
- alignment styling has been exported to a single location

## Tasks
- [ ] Discuss in the team which solution will fit better the future needs
- [ ] Implement new styling
- [ ] Clean up all components having this replicated code

**Comment by weilbith** [comment]
@taleldayekh here we go

**Comment by taleldayekh** [comment]
> @taleldayekh here we go

Thank you for adding the issue.
