### ISSUE TITLE
Try GitHub code scanning

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2200]
## Description

GitHub integrated a new code scanning tool: https://github.blog/2020-09-30-code-scanning-is-now-available/

It is rules based and free to use, so we should give it a try, look at the results and decide if it's warnings are meaningful enough to use it.

## Acceptance criteria
- 

## Tasks
- [ ] Enable code scanning on the repo
- [ ] Go through the results and evaluate results
- [ ] Decide whether to leave it enabled or not

**Comment by palango** [comment]
Output is not helpful at the moment: https://github.com/raiden-network/light-client/pull/2545
