### ISSUE TITLE
Enable performance analysis tool for scenario runs

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2243]
## Description

The scenario player has a tool that calculates performance metrics for each scenario. We should enable this for the light client as well.

This might be as easy as just running it on the logs or having to adjust some regexes.

## Acceptance criteria
- Have the script run for each scenario and log the results to rocket chat

## Tasks
- [x] Research if the script works on node or scenario player logs
  - The script uses the node logs to calculate the number of hops in a  transfer. We might need to adjust some filters there.
- [x] Enable the script for LC scenario runs
  - Basic analysis works
- [x]  Adapt the node log parsing to work with the light client

**Comment by christianbrb** [comment]
@palango This is already working, right?

**Comment by palango** [comment]
Yes, the basics work.

There is a feature that automatically detects how many hops a transfer had and displays that as well. That needs some further investigation to work again.

**Comment by christianbrb** [comment]
@palango Thanks :)
I think this is fine for the moment :)
