### ISSUE TITLE
One scenario for mainnet testing

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2346]
## Description
We decided to create one simple scenario for mainnet testing.

## Acceptance criteria
- One scenario is defined
- It is executed on mainnet one time

## Tasks
- [x] Review if BF1 would work for this
- [x] Update the scenario player, so that it works for mainnet
- [ ] Execute the scenario on mainnet
  - [ ] Requires testnet presence fixes to be enabled on mainnet

**Comment by palango** [comment]
BF1 does tests the following functionality of the client:
- Starting and stopping of nodes
- Channel opening and closing
- Deposits and withdraws
- PFS interactions
- MS interactions

**Comment by christianbrb** [comment]
We have to fix the scenario runs first: https://github.com/raiden-network/light-client/issues/2361

**Comment by christianbrb** [comment]
Waiting for Monitoring Service problems to be resolved.

@karlb Is there an issue?

**Comment by karlb** [comment]
Now there is: https://github.com/raiden-network/raiden/issues/6756

**Comment by palango** [comment]
Tracked in https://github.com/raiden-network/team/issues/896
