### ISSUE TITLE
I want to use an Alderaan Raiden Network with just paying a hub 

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#244]
## User Story
As Chris I want to use an Alderaan Raiden Network with just paying a hub so that I can quickly get started

## Acceptance criteria
- Messages are compatible
  - New HashFunction (sha256) is used (see https://github.com/raiden-network/raiden-contracts/pull/979)
  - Hash of Locks instead of MerkleTree	
  - Fee = 0
  - Route = Static (Light Client -> Hub)
  - No PFS
- Hub is the target
- No mediated transfers
- ~~Don’t answer to channel withdraw message~~ Handle WithdrawRequest (send WithdrawConfirmation) and WithdrawExpiration (send Processed)
- We cannot send a transfer where we don't have a direct channel
- Feature branch for Alderaan (`next`)
- Pulling new contracts
- Maintain the Red Eyes branch (pull patches from Alderaan - backporting - self-containing PRs after it has been merged to the Alderaan branch)
- We don't change something in the dApp

## Tasks

- [x] Create a skeleton on a different branch @andrevmatos 
- [x] Adapting to the new contract
    - [x] Changing the MerkleTree to an array of locks
    - [x] Change the HashFunction to sha256
    - [x] Check all message fields and compare with new contract
    - [x] Set the route (address light client to address hub in the metadata field
    - [x] Upgrade the contracts.json

**Comment by christianbrb** [comment]
### Raiden message spec:
https://raiden-network-specification.readthedocs.io/en/latest/messaging.html#locked-transfer

### Route
[Route Metadata](https://github.com/raiden-network/raiden/blob/c9e85286f75c3af245a7d330fed40558db206e6c/raiden/messages/metadata.py#L11)
[metadata](https://github.com/raiden-network/raiden/blob/develop/raiden/messages/transfers.py#L403)

**Comment by christianbrb** [comment]
[Last contracts release](https://github.com/raiden-network/raiden-contracts/releases) before [Alderaan ](https://github.com/raiden-network/raiden/milestone/14) is planned for tomorrow

CC @Dominik1999

**Comment by kelsos** [comment]
@christianbrb I went and renamed everything from Ithaca to Alderaan in the issue.

**Comment by andrevmatos** [comment]
Split in #289, #290, #291, implemented in #293, #294 , #295 and #304
