### ISSUE TITLE
dApp - strictly manual update procedure

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#2440]
## Description

Follow up of #2414

At the moment the updates to the dApp happen in some kind of automated manner. The updates are tight to a new (according to byte order) server worker script. This means each time the dApp gets build, not matter if anything has changes, this means an "update". The service worker itself checks every 60s if there is an update for itself. Note that webbrowsers do so themselves every 24h automatically anyways. The check for an update of a service worker also implies (and is not devisable) the download of the new script, its parsing and installation. Then it waits in the pipe until it can displays the currently active service worker. This happens automatically when the active service worker thread got stopped (e.g. new start of web-browser, revisit domain after all related tabs where closed etc.). Or it can be manually triggered to get immediately activated. This is basically what the current update notification does. Note that this does only activate the new service worker with an updates cache, but this does not unload the active version until the next load of the dApp.

Summarized we do not strictly serve the dApp from cache once a version got downloaded. Updates are tight to service worker updates which happen uncontrolled, can't be confirmed by the user, can't be denied, get applied automatically anyways.

## Acceptance criteria
- [x] The dApp must be served 100% offline after the first initial pre-caching.
- [x] Update for a new version of the dApp must be independent form the service worker update procedure.
- [x] The user must be notified of a new version before it gets fetched.
- [x] An update gets only applied when a user actively confirms it.
- [x] A confirmed update gets applied actively, means it requires to shutdown the SDK, apply update and load new version.
- [x] The shutdown of the SDK **must not** remove the local state including the key (currently sleeping bug in code)
- [x] The service worker must be able to detect that a user cleared the browser cache, which should result into a fresh new version.
- [x] The service worker must react to a (partially) deleted or corrupted cache during the runtime of the dApp.

## Tasks
- [ ] 

---

Note that this issue got created a while after there was already a massive amount of work and research invested into this base "feature", until it has been decided to make this its own issue. Therefor it includes more detailed criteria.

**Comment by weilbith** [comment]
Soft requirements:
  - [ ] As now complex logical part of the dApp, it should be written in TypeScript
  - [ ] Use the `workbox` library directly and get rid of the `vue-cli-pwa` plugin

**Comment by weilbith** [comment]
Using TypeScript for the service worker related sources is a bigger issue. This requires the `webworker` library during the stranspilation of TypeScript. Apparently it seems to interfere with the other libraries we use already.

**Comment by weilbith** [comment]
Since the process with the shutdown of the SDK has changed, I now have the opportunity to make code a bit cleaner and put the service worker assistant (part in the "main" thread that communicates with the service worker thread) into a Vue plugin. The same as we do for example for the Raiden service etc.

**Comment by weilbith** [comment]
There appear to occur issues with the offline serving. I did test "rounds" where everything worked perfectly. But sometimes I had cases where I did not work. In fact there are errors that JavaScript or CSS chunks could not be fetched, but they are available in the cache. I checked that manually. I have absolutely no clue why they occur. I tried to get an idea by extending the logging. But that hasn't worked out so well. I need to invest time to understand that.
Furthermore it worries me that for such cases the network gets used. I need to block these requests. But I can't just block everything. We need the connection to matrix and also other sub-pages like the docs must work via network. But since the route match function for the pre-cache seem to fail sometimes, this is the actual issue to investigate. Just don't know yet how.

**Comment by weilbith** [comment]
Observation:
Fresh start without any cache, nor already active service worker. Starting local web-server and load the page. The service worker gets installed and activated. It fills the cache with the current version.
Now kill the web-server. Trying to access "new" parts in the dApp is not possible due to missing asset chunks. Cache actually includes all these reported assets. The established logging of the route handler is completely silent.
Keep the server offline, but reload the dApp in the web-browser. The page gets successfully loaded from cache and everything is accessible now. The logging of the route is working as well.

So I think the establishment of the route is not working correctly for the first time loading. I'm not sure if this is related to the register, install and activation lifecycle or something else. I'll find it out.

**Comment by weilbith** [comment]
Sorry for the many updates, but I'm quite confused atm. I tried to replicate my observation and test different solution approaches. But when I now reload the page the cache gets cleared automatically...

**Comment by weilbith** [comment]
I'm removing the `register-service-worker` package. We use only a tiny part of it. But there is too much going on inside. I rather have more direct control over the registration. The number of lines of code should not vary.

**Comment by weilbith** [comment]
Alright. As result of the manual registration I also let the service worker explicitly claim control of the clients. This was apparently not happen sometimes. Thereby we route gets active and the cache works right away. This means I can load the page the first time, shutdown the server and from then on operate the dApp standalone (without reload or anything).

Now I'll concentrate on a corrupted cache again. I found the catch handler of workbox. Combined with controller I eventually could do a validation in periodic manner.

**Comment by weilbith** [comment]
Without much information I'm about to add an enum for service worker messages and start to use the Vuex store for the assistant.

**Comment by weilbith** [comment]
Important improvement: embed the active version inside the package itself and do not fetch it on loading. This is just stupid.

**Comment by weilbith** [comment]
Code looks pretty good now I think. Still the full TypeScript support is missing.
Working on the cache corruption detection now.

**Comment by weilbith** [comment]
Alright. Cache issues during runtime with an available client to handle user interactions is fixed in a catch manner. I'm now adding the special case when no client is available (e.g. cache got cleared while dApp not open).

**Comment by weilbith** [comment]
Alright. I'm done for today. Tomorrow I'll see what I can do to convert most (hopefully all) of the service worker script into Typescript.
Afterwards I'll clean up everything, see where tests are possible (many parts can't be tested via units) and finally redo everything with a clean history. Let's see how I can split up the big thing into smaller standalone commits.

**Comment by weilbith** [comment]
Out of curiosity I did a light house test again. Unfortunately we lost the integration of the manifest for the PWA. I'll make sure it gets registered again. This should make the dApp able to get installed. Unfortunately it still complains about a too slow start because it is so huge. This is not critical. But we should start to use more a-la-cart.

**Comment by weilbith** [comment]
Just to be more secure I added a regular check for the cache validity. So the user must not first try to interact to let it fail. This is better in terms of that the cache could be partially broken. In such case he could start to do something in the app, but then at a critical point it fails because this source is not cached. This can prevent that, according to the cycle time.

**Comment by weilbith** [comment]
Manifest is injected again. Lighthouse report is green for PWA installation. I tested it and I can install it and run the dApp via my OS application launcher.

**Comment by weilbith** [comment]
Alright. I'm trying to do my best to integrate the `webworker` library for TypeScript. @andrevmatos was so kind to do some research this night (ECT) and sent me [this documentation](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-lib-). Let's see what it can do.

**Comment by weilbith** [comment]
One minor thing I eventually will do is to replace the `fetch` for the version file with an `XMLHttpRequest`. Because now I can't catch the error of fetch completely. Nevermind I catch it, `fetch` will always report itself to the console. This is quite annoying and noise. Furthermore it reports an error, while we only print a warning.

**Comment by weilbith** [comment]
TypeScript conversion mainly done. Getting some compilation errors again.. :expressionless:

**Comment by weilbith** [comment]
Found my mistake. It can't work to exclude files in `tsconfig.json` if you then import them in includes files... :see_no_evil:

**Comment by weilbith** [comment]
Alright. We have time issues. So I stopped trying to merge the TypeScript libraries. I switched to plain JavaScript for the worker exclusively again. I put everything into a commit and pushed it as a backup to my fork. 
After all this are just about ~500 lines of code. But they are pretty much packed with features, special case treatment and general rework of many things. Furthermore where there no test adoptions/extensions yet. So it is time to redo everything step by step in meaningful commits that are understandable, reasonable and reviewable. Here is my attempt to create a list of changes that should belong into standalone commits :

- tiny fix: raiden service shutdown navigates to home
- tiny preparation: raiden service shutdown resolves with promise
- manifest extension and manual registration
- Vue plugin to register service worker manually
- remove vue-cli-pwa plugin and use workbox directly
- service worker does install and activation manually
- version file generation
- introduce assistant to fetch version and extend Vuex store (remind package version plugin)
- update snackbar use Vuex store (remind to remove custom window event)
- trigger update feature (worker, assistant, snackbar)
- catch handler in worker (worker, assistant, store, snackbar)
- establish regular cache integrity check (worker, assistant)

**Comment by weilbith** [comment]
Bonus (because I'm motivated): visually show the user that the application can be installed as PWA. This looks nice and make it more dominant at the desktop environment. This is quite easy to achieve by just listening to some events on the window object that the web-browser triggers.

**Comment by weilbith** [comment]
In-between I need to figure out how I can uninstall the PWA again for testing. :expressionless:

**Comment by weilbith** [comment]
Ups, there seem to be a bug in the cache validity check. It always triggers a mandatory update. :see_no_evil:

**Comment by weilbith** [comment]
Alright, I'm done. I just pushed the feature branch. I'll open the PR tomorrow morning. This PR will require a lot of description and especially manual test instructions.

**Comment by weilbith** [comment]
I resolve the merge conflicts now. I'll need to do it anyway, so better do it now.

**Comment by weilbith** [comment]
What just came into my mind: I think we should disable the service worker on staging. It is kinda "against" the idea of staging.

**Comment by christianbrb** [comment]
@weilbith Thanks for your transparency during the development process :) 

We should enable it on staging. It would be the best way to continuously test it as it is getting frequently updated.

**Comment by weilbith** [comment]
Hmm. Okay, you have a good point. Let's see how we can do that. The issue is that staging is always the same release version, until we finally make the next release with all these changes. This means staging will never show you that there is an update. Though you still force to get the update using the developer tools of your web-browser. But that is not really the ideal solution for a daily basis, isn't it?

**Comment by christianbrb** [comment]
Cool, thanks :) Let's chat, if you need more input.

**Comment by weilbith** [comment]
Fu**. I discovered an issue while writing the PR description. Oh no come on. :cry:
