### ISSUE TITLE
I want to send payments to any Raiden client with paying mediation fees

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#246]
## User Story
As Chris I want to send payments to any Raiden client with paying mediation fees so that I can send tokens to every client.

## Acceptance criteria
- Send the amount + expected fees provided by PFS + 10%
- The option [findRoutes ](#359) is used to request a path + fees from the LC
- If the user is accepting the path + fees the metadata is constructed and transfered to the LC
- Using the Deposit-Pop up
- Not setting `diversity_penalty` and `fee_penalty`
- Capacity updates are sent to the PFS
- [Workaround ](https://github.com/raiden-network/light-client/pull/360/files#diff-4dcc2ade77ff6c582c536559ed1af73dR824) is rolled back partly

## Tasks
- [x] Finalize tests for #366 
- [x] Implement a function to return the fees
- [x] Implementation in dApp

After #245 

## Docs

Mediation fee specs: https://raiden-network-specification.readthedocs.io/en/latest/mediation_fees.html
PFS Returns: https://raiden-network-specification.readthedocs.io/en/latest/pathfinding_service.html#returns
How to send capacity updates: https://raiden-network-specification.readthedocs.io/en/latest/pathfinding_service.html#capacity-and-fee-updates

**Comment by christianbrb** [comment]
Within #330 
- The LC requests the route (from the PFS) from the Raiden hub to the target, because the light client does not publish channel information to the PFS and therefore (at least with the current PFS design) doesn't get back a route from the LC to the target)
- The route from the LC to the hub is concatenated with the route from the PFS and put together in the metadata field.

This has got the drawback, that the LC doesn't get the fee estimation from the hub.

There are three potential solutions:
1. Publish information from the LC to the PFS
2. Get information about the route from the LC to the target without the need to publish information to the PFS (new feature for the PFS?) 
3. Add a fee estimate for the first hop like the full client is doing it if using local routing (see https://github.com/raiden-network/raiden/pull/4760/files)

@palango @karlb Any other thoughts or proposals?

**Comment by karlb** [comment]
> Get information about the route from the LC to the target without the need to publish information to the PFS (new feature for the PFS?)

I think this is the way to go. But I don't have and idea on the specifics, yet.

**Comment by christianbrb** [comment]
Which route do I get, if I do not set the two optional parameters `diversity_penalty` and `fee_penalty`
From the docs: `If those parameters are omitted, reasonable defaults are chosen.`

I would go with the defaults and not setting the two parameters (trusting the vendor ;-) )

**Comment by karlb** [comment]
> Which route do I get, if I do not set the two optional parameters `diversity_penalty` and `fee_penalty`

Current defaults are
```
DIVERSITY_PEN_DEFAULT: int = 5
FEE_PEN_DEFAULT: int = 100
```
meaning that
* reusing one node that is already used in a previous route (in the same PFS response) is as bad as adding five more hops to the route
* incurring fees of 1 RDN is as bad as adding 100 more hops to the route

**Comment by nephix** [comment]
https://github.com/raiden-network/light-client/pull/360/files#diff-4dcc2ade77ff6c582c536559ed1af73dR824 should be addressed here

**Comment by christianbrb** [comment]
Related: https://github.com/raiden-network/raiden/issues/4991
