### ISSUE TITLE
Write e2e test from a use-case perspective

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2582]
## Description
Some of our integration tests are better suited as e2e testa and should therefore be converted as such.

## Acceptance criteria
- Better distinction between integration tests and e2e tests.

## Tasks
- [ ] Identify which integration tests are better suited as e2e tests.
- [ ] Re-write integration tests to be e2e tests.

**Comment by taleldayekh** [comment]
- [ ] Write e2e test from a use-case perspective
- [ ] Remove current integration tests
