### ISSUE TITLE
Run e2e test in the PRs

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2586]
## Acceptance criteria
- A PR should also include e2e tests.

## Tasks
- [ ] Insert e2e tasks in the PRs.
- [ ] Remove nightlies since e2e will run on each PR now?
- [ ] Investigate how intermediate steps can be cached to reduce test running times.
- [ ] Make sure coverage is not effected negatively.
