### ISSUE TITLE
Refactor unit tests

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2588]
## Description
This can be difficult/challenging to do.

## Acceptance criteria
Write test for those functions:
- [x] `synced: Promise<raidenSynced['payload'] | undefined> = makeSyncedPromise(this.action$);` (@andrevmatos)
- [x] `getTokenInfo = makeTokenInfoGetter(this.deps);` (@andrevmatos)
- [x] `userDepositTokenAddress: () => Promise<Address> = memoize(` (@andrevmatos)
- [x] `static async create<R extends typeof Raiden>(` (@andrevmatos)
- [x] `async start(): Promise<void> {`
- [x] `get started(): boolean | undefined {`
- [x] `async stop(): Promise<void> {`
- [x] `get log() {`
- [x] `get state(): RaidenState {`
- [x] `get address(): Address {`
- [x] `get mainAddress(): Address | undefined {`
- [x] `get network(): Network {`
- [x] `async getBlockNumber(): Promise<number> {`
- [x] `updateConfig(config: PartialRaidenConfig) {`
- [x] `async getAvailability(`
- [x] `async monitorToken(token: string): Promise<Address> {`
- [x] `async dumpDatabase() {` (@andrevmatos)
- [x] `getBalance(address?: string): Promise<BigNumber> {` (@palango)
- [x] `async getTokenBalance(token: string, address?: string): Promise<BigNumber> {` (@palango)
- [x] `async getTokenList(): Promise<Address[]> {` (@andrevmatos)
- [x] `async openChannel(` (@agatsoh)
- [x] `async depositChannel(` (@agatsoh)
- [x] `async withdrawChannel(` (@agatsoh)
- [x] `async closeChannel(` (@agatsoh)
- [x] `async settleChannel(` (@agatsoh)
- [x] `async transfer(` (@palango)
- [x] `async waitTransfer(transferKey: string): Promise<RaidenTransfer> {`
- [x] `async findPFS(): Promise<PFS[]> {`
- [x] `async findRoutes(`
- [x] `async directRoute(`
- [x] `async mint(` (@andrevmatos)
- [x] `async getUDCCapacity(): Promise<BigNumber> {`
- [x] `async getUDCTotalDeposit(): Promise<BigNumber> {`
- [x] `async depositToUDC(`
- [x] `async transferOnchainBalance(` (@palango)
- [x] `async transferOnchainTokens(` (@palango)
- [x] `async getUDCWithdrawPlan(): Promise<`
- [x] `async planUDCWithdraw(value: BigNumberish): Promise<Hash> {`
- [x] `async withdrawFromUDC(value?: BigNumberish): Promise<Hash> {`
- [x] `async suggestPartners(` (@palango)

## Tasks
- [x] Write test for each public method and property in the Raiden class
- [ ] Convert epics unit test to be more of actual unit tests
- [ ] Identify what the requirements are for us to be happy
- [ ] Mark difficult tests for later improvements
- [ ] Refactor some of the epics
