### ISSUE TITLE
Mobile dApp: Implement private key import and provide RPC endpoint

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2598]
## User Story

As Chris I want to connect to the dApp mobile on iOS and Android by importing my private key and providing my own RPC endpoint.

## Acceptance criteria

The mobile dApp should have an interface where a users can import their private key and provide an RPC endpoint.

## Tasks

Work can start on all tasks below except the interface task which is dependant on #2631  .

- [ ] Understand security and encryption issues involved when importing a private key (not only importing the JSON but also typing the. mnemonic). See [this comment](https://github.com/raiden-network/light-client/issues/2598#issuecomment-790532170) for more details
- [ ] Implementation
- [ ] Create interface for users to provide their own RPC endpoint.
- [ ] Disable Raiden account (using your own private key is like already having a Raiden account).

**Comment by taleldayekh** [comment]
@weilbith look into first task before we make an estimate.

**Comment by weilbith** [comment]
We had a meeting today with Daniel from the Trustlines team. They already went through this struggle and shared some information with us. Though, their security requirements for Trustlines which uses mutual credit are different than ours.

Here some chunks of collected information:
  - using EthersJS to encrypt/decrypt the private key takes 3 minutes on a mobile device
  - there is a  keychain APIs on iOS to store secrets, encrypted with the users biometric information (its fast)
  - on Android the keychain stuff does not work so well, so they ended up to store it in the async store
  - other applications have no access to the data of other devices
  
Questions:
  - Where to draw the line of security? (e.g. thief has phone and can read block storage device)
  - How secure must we be in relation to usability and development effort
  
Capacitor:
  - There is [community plugin](https://github.com/ionic-team/cordova-plugin-ios-keychain) which provides access to they iOS keychain
  - There is [universal and professional plugin](https://ionic.io/products/identity-vault) for enterprise customers that works for iOS and Android for diverse purpose of secure data management
  - there is the localStorage we already use for the user configuration with any encryption which could get extended generically by using [secure-ls](https://github.com/softvar/secure-ls) in combination with the already in-use Vuex persistence to encrypt the data in the localStorage (note that localStorage is documented to be not tooo reliable)
