### ISSUE TITLE
Mobile dApp: Implement wallet connect and provide RPC endpoint

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2599]
## User Story

As Chris I want to connect to the dApp mobile on iOS and Android by using wallet connect and providing my own RPC endpoint.

## Acceptance criteria

The mobile dApp should allow a users to connect using wallet connect and their own RPC endpoint.

## Tasks

Work can start on all tasks below except the interface task which is dependant on #2630 .

- [ ] Add the wallet connect TypeScript dependency for giving the mobile dApp access to user wallets.
- [ ] ~~Create interface for connecting using wallets and for users to provide their own RPC endpoints.~~ Should be tackled in #2630 
- [ ] ~~Research and understand drawbacks and how to mitigate drawbacks of the bridge server.~~
- [x] Research how sessions can be saved (so users can continue where they left of after exiting the mobile dApp).
