### ISSUE TITLE
dApp mobile: List necessary UI adjustments for making dApp look good on "all" screens

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2604]
## Description

The UI for the mobile version of the dApp should not break in either functionality or layout. **Please write you name next to the title in the comment with the UI parts you are working on**.

## Acceptance criteria
- The mobile dApp works and looks good on iOS and Android.

## ToDo
- [ ] Make the dApp look good from screen size **320x568** and up

## Tasks
- [x] Test on different screen sizes and browsers (look up css break points for mobile)
- [ ] Safe zone margins
- [ ] Create new issues if bigger layout changes needs to be made.

**Comment by palango** [comment]
## iOS emulator

Results looks quite well to me

![Simulator Screen Shot - iPhone 12 - 2021-03-03 at 15 56 11](https://user-images.githubusercontent.com/90851/109834561-9dad5400-7c42-11eb-9e01-685b3b552b81.png)
![Simulator Screen Shot - iPhone 12 - 2021-03-03 at 15 56 54](https://user-images.githubusercontent.com/90851/109834575-a1d97180-7c42-11eb-84ad-75415345d270.png)
![Simulator Screen Shot - iPhone 12 - 2021-03-03 at 15 57 35](https://user-images.githubusercontent.com/90851/109834578-a2720800-7c42-11eb-8322-2b7b698b8573.png)
![Simulator Screen Shot - iPhone 12 - 2021-03-03 at 15 55 34](https://user-images.githubusercontent.com/90851/109834583-a3a33500-7c42-11eb-8028-33a3ab1f3867.png)
![Simulator Screen Shot - iPhone 12 - 2021-03-03 at 15 54 36](https://user-images.githubusercontent.com/90851/109834586-a4d46200-7c42-11eb-8065-9c16e2cc71be.png)

**Comment by taleldayekh** [comment]
Looks the same for me, so wonder how come the layout was overlapping on the initial run.

**Comment by agatsoh** [comment]
I tested the dapp on a bunch of different mobiles and tabs viewport the only real screen where I encountered some problem is the screen which you see below (and this was also due to low resolution low viewport mobile). My laptop is fortunately touch screen I didnt realise that earlier but I have tried this using my laptop in touch screen mode and the buttons are mostly responsive.
In lower resolution or lower viewports there is a scroll which is introduced which does not break or introduce any wierd CSS glitches when the keyboard is brought up which is a pretty good sign.


![android_emulator_issues](https://user-images.githubusercontent.com/15123108/110792164-0f1b8100-8299-11eb-851d-80fb66d51964.png)

**Comment by taleldayekh** [comment]
TODO: Test on different screen sizes and browsers.

**Comment by taleldayekh** [comment]
## Backup State

![lightclient raiden network_staging_(iPhone 5_SE) (1)](https://user-images.githubusercontent.com/43838780/115212830-37509800-a101-11eb-89ea-ea14d8758b4a.png)

- [ ] Fix broken header
- [ ] Make scrollbar "invisible", remove blue scrollbar

**Comment by taleldayekh** [comment]
## UDC

- [ ] Fix broken info overlay
- [ ] Fix broken withdrawal dialog

![lightclient raiden network_(iPhone 5_SE) (1)](https://user-images.githubusercontent.com/43838780/115214169-877c2a00-a102-11eb-95ce-7fd6767c1601.png)

![lightclient raiden network_(iPhone 5_SE) (2)](https://user-images.githubusercontent.com/43838780/115214390-c0b49a00-a102-11eb-8618-ad61f6f4b19e.png)

**Comment by taleldayekh** [comment]
## Open Channel

- [ ] Fix broken header
- [ ] Fix broken info overlay

![lightclient raiden network_(iPhone 5_SE)](https://user-images.githubusercontent.com/43838780/115216394-beebd600-a104-11eb-9f23-c489a348e397.png)

![lightclient raiden network_(iPhone 5_SE) (1)](https://user-images.githubusercontent.com/43838780/115216432-c8753e00-a104-11eb-9823-c144c8632870.png)

**Comment by taleldayekh** [comment]
## Select Hub

- [ ] Fix broken mint token dialog

![lightclient raiden network_(iPhone 5_SE)](https://user-images.githubusercontent.com/43838780/115216610-f3f82880-a104-11eb-98bd-8e4edcaf60c8.png)

**Comment by taleldayekh** [comment]
## Transfer

- [ ] Fix broken info overlay
- [ ] Fix out of shape + icon in "Change Token" overlay

![lightclient raiden network_(iPhone 5_SE)](https://user-images.githubusercontent.com/43838780/115218591-01161700-a107-11eb-9f95-82416a50fb05.png)

![lightclient raiden network_(iPhone 5_SE) (1)](https://user-images.githubusercontent.com/43838780/115218629-0b381580-a107-11eb-8fdc-174aa70f3aa3.png)

**Comment by taleldayekh** [comment]
## Channels

- [ ] Fix broken info overlay
- [ ] Make withdrawal icon visible
- [ ] Fix broken close channel dialog

![lightclient raiden network_(iPhone 5_SE) (2)](https://user-images.githubusercontent.com/43838780/115219057-71249d00-a107-11eb-8851-05a35f74cfd3.png)

![lightclient raiden network_(iPhone 5_SE) (3)](https://user-images.githubusercontent.com/43838780/115219095-784bab00-a107-11eb-964a-dbaf7ce1d0fe.png)

![lightclient raiden network_(iPhone 5_SE)](https://user-images.githubusercontent.com/43838780/115219130-7f72b900-a107-11eb-9363-bf42762ff344.png)

**Comment by taleldayekh** [comment]
## Notifications

- [ ] Fix broken card layout

![lightclient raiden network_(iPhone 5_SE) (1)](https://user-images.githubusercontent.com/43838780/115219299-b052ee00-a107-11eb-999b-468f3b37278d.png)

**Comment by taleldayekh** [comment]
## Account

- [ ] Fix horisontal scrolling due too long address
- [ ] Fix account menu items (seems to be only displaying three and missing the rests)

![lightclient raiden network_(iPhone 5_SE) (1)](https://user-images.githubusercontent.com/43838780/115219832-2bb49f80-a108-11eb-9ed5-56f66592c902.png)

**Comment by taleldayekh** [comment]
## Direct Transfer

- [ ] Fix broken info overlay

![lightclient raiden network_(iPhone 5_SE)](https://user-images.githubusercontent.com/43838780/115220103-76ceb280-a108-11eb-8866-f217f0cd1eaf.png)

**Comment by taleldayekh** [comment]
## Mediated Transfer

- [ ] Fix transfer summary which breaks when there is a lot of information
- [ ] Fix PFS list

![lightclient raiden network_(iPhone 5_SE) (1)](https://user-images.githubusercontent.com/43838780/115233760-966dd700-a118-11eb-8f67-627038dabd95.png)

![lightclient raiden network_(iPhone 5_SE)](https://user-images.githubusercontent.com/43838780/115233794-9f5ea880-a118-11eb-9187-6ca93bdc5ba1.png)
