### ISSUE TITLE
Add `user_deposit` endpoint to CLI

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/light-client#2612]
## Description
For interacting with the UDC, I added a `/user_deposit` endpoint recently to the python client's API. To follow up the light client should implement it as well.

From the original PR (https://github.com/raiden-network/raiden/pull/6821):
> It has three possibilities for POST requests depending on the body parameter:
> - deposit: `{total_deposit: <amount>}`
> - plan a withdraw: `{planned_withdraw_amount: <amount>}`
> - withdraw: `{withdraw_amount: <amount>}`

All return a `transaction_hash` after the tx was minted. The planning of a withdrawal additionally returns the number of blocks until the funds can be withdrawn (`planned_withdraw_block_number`).

For more details see the docs: https://raiden-network.readthedocs.io/en/latest/rest_api.html#user-deposit-for-services

## Acceptance criteria
- Implement the endpoint as in the documentation.

## Tasks
- [ ] Add new endpoint: `/user_deposit`
- [ ] Add deposit method
- [ ] Add plan a withdrawal method
- [ ] Add withdraw method

**Comment by weilbith** [comment]
Sorry that I missed to provide a status update. Due to the differences how both clients implement the handling of the user deposit contract, we need to wait for #2629 for the parts we can't translate/hide in the server part, but require actual changes in the SDK.
