### ISSUE TITLE
Mobile dApp: Get credentials for publishing apps

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2632]
## Description

To publish apps on Apple App Store (and Goole Play?) we need a dev account and a subscription.

## Acceptance criteria
- Should be able to publish apps on Apple App Store and Google Play.

## Tasks
- [x] Check requirements for Google Play
- [x] Decide relevant organisation
- [ ] Acquire Apple Developer account and Google Console account

**Comment by taleldayekh** [comment]
This [separate issues](https://github.com/raiden-network/team/issues/927) has been created to tackle this.

**Comment by taleldayekh** [comment]
We will most likely not proceed with a "native" mobile dApp.
