### ISSUE TITLE
Adapt unstable contracts

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2669]
## Description

Related to https://github.com/raiden-network/light-client/issues/2514

We now have `unstable` and `development` contracts.

## Acceptance criteria
- 

## Tasks
- [ ] Make `unstable` contracts selectable in LC
- [ ] Add `development-environment` option in CLI
- [ ] Update deployments
  - [ ] `stable` uses *demo* contracts
  - [ ] `unstable` uses *unstable* contracts
