### ISSUE TITLE
Make CLI easily installable

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2789]
## User Story

As Chris, I want an easy way to install and use the light clients CLI. Ideally I just need to install a `raiden-cli` package and then can run it with the same parameters as the PC provides with `npx raiden-cli`

## Acceptance criteria

- Be able to install and run the CLI with the minimum amount of hassle
- Have this documented

## Tasks

- [x] Decide on a name for that package
- [ ] Build and publish package on npm
  - [x] Check changelog, version bumping, ...
  - [ ] Extend CircleCI config to upload package
- [ ] Document installation/usage

**Comment by weilbith** [comment]
I just discussed with @taleldayekh that do not want to release the old `v0.16.0` tag, but just do it when we make the next release together with the `raiden-ts` package.

**Comment by weilbith** [comment]
Version bumping is working for all workspaces in the repository already. Nothing to do there.

The CHANGELOG does also exist and is up-to-date. It gets maintained together with all other CHANGELOGs.

**Comment by weilbith** [comment]
For the naming I would say we have one: `raiden-cli` 
Though I'm not too happy with it, it is used everywhere all other the place. The package like that basically exists already for a while. Just that is was never uploaded to this specific package registry. So I would not "break" it now.

**Comment by weilbith** [comment]
The open points except the naming have been addressed in the above linked PR. I'm still thinking of testing it with a private registry repository. But in worst case it is as usual: do the sh** manually if it fails in CI. 🤷🏾
