### ISSUE TITLE
Set mainnet mediation fee defaults

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2790]
We need to set mediation fee defaults for mainnet in the CLI.

Ref https://github.com/raiden-network/team/issues/881

## Tasks
- [x] Set default fixed fee: https://github.com/raiden-network/raiden/blob/develop/raiden/utils/mediation_fees.py#L34-L35
- [x] Set default proportional fee: https://github.com/raiden-network/raiden/blob/develop/raiden/settings.py#L78
- [x] Set default imbalance fee: https://github.com/raiden-network/raiden/blob/develop/raiden/settings.py#L79-L81
- [x] Set default cap fees setting: https://github.com/raiden-network/raiden/blob/develop/raiden/settings.py#L113

**Comment by andrevmatos** [comment]
`cap_fees` has a `true` default in the SDK, but it's not a problem to set it also in the CLI. The others should have its default set in CLI's `config.json`. If you set `config.mediationFees[AddressZero] = { flat: ..., cap: ..., }`, that config will be used as a fallback if no specific config is set for a given token address. Notice that his config is per whole config object, not per fee model, so e.g. setting `config.mediationFees[tokenAddr] = { flat: 1 }` will make it the flat fee for tokenAddr be 1 and all the others be 0, even if something higher is set for `AddressZero`.

**Comment by weilbith** [comment]
Does this also apply that we want to enable the capability `Mediate` per default in the CLI?

**Comment by palango** [comment]
> Does this also imply that we want to enable the capability `Mediate` per default in the CLI?

I already did this in https://github.com/raiden-network/light-client/commit/a5bc94fcd18b78be86331704eac7e67eeb61e19e

**Comment by weilbith** [comment]
> > Does this also imply that we want to enable the capability `Mediate` per default in the CLI?
> 
> I already did this in https://github.com/raiden-network/light-client/commit/a5bc94fcd18b78be86331704eac7e67eeb61e19e

Ah okay. I though our defaults in regard of configuration are exclusively in the `config.json`. Especially as the other capability is also there. So it is an awkward mix. But I assume you need a boolean default if you have this option for the user?
