### ISSUE TITLE
Cooperative settlement

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2839]
## User Story

As Chris, I want to cooperatively settle my channels when possible, so that I save time and money.

## Acceptance criteria

- [ ] Cooperative settlement implemented in the SDK
- [ ] Cooperative settlement added to the CLI
- [ ] ~~Cooperative settlement added to the dApp~~

## Tasks

- [ ] Create sub-issues to track progress of the implementation in the sub-components
- [ ] Update contracts to a version with cooperative settlement (see https://github.com/raiden-network/raiden-contracts/pull/1474)
- [ ] Implement sub-component changes
- [ ] Adapt e2e tests to include cooperative settlement

## Resources
- https://github.com/raiden-network/raiden-contracts/pull/1474
- https://hackmd.io/1_MkYDcZQaem_r6dkJ0LHg?both
- https://github.com/raiden-network/team/issues/938

**Comment by taleldayekh** [comment]
Close when #2850 #2876 are finalised.
