### ISSUE TITLE
dApp: Cooperative settlement 

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2851]
## User Story

As Chris I want to close and settle using cooperative settlement when using the dApp.

**Alternatively this can be done on the SDK side only and no dApp implementations would then be needed**

## Acceptance criteria

- [ ] Need to maintain backward compatibility so that we can close and settle channels the traditional way.
- [ ] Find a solution that either replaces the current UI or at least does not make it cluttered.

## Tasks

- [ ] Discussions
- [ ] Implement outcome of discussion

**Comment by taleldayekh** [comment]
Cooperative settlement won't be implemented on the dApp side.
