### ISSUE TITLE
Upgrade blockchain calls to be compatible with Alderaan contracts

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#290]
## Description

After #289, the tests should be broken as a few interfaces changed on the `raiden-contracts` since Red Eyes (0.4.0). We must first check each method and event we use/listen to, and update our codebase to be compatible with it. All our blockchain interaction happens under the [raiden-ts/src/channels](https://github.com/raiden-network/light-client/tree/master/raiden-ts/src/channels) submodule.

## Acceptance criteria
- channels Epics can interact with and listen to new contracts methods and events
- blockchain tests pass. not all tests need to, as messages may still require updates
- Work is done in the `next` branch

## Tasks
- [x] Update [locks hashing utils](https://github.com/raiden-network/light-client/blob/master/raiden-ts/src/transfers/utils.ts) to use ~~`sha256` instead of `keccak256` (also available in `ethers/utils`)~~ the keccak hash of the concatenated list of locks, instead of the merkle tree root, adapt tests.
- [x] Update the secrethash to be the `sha256` has of the `secret`, instead of the `keccak256`
- [x] Check and if needed update channel open call and `ChannelOpened` event monitoring
- [x] Check and if needed update channel setTotalDeposit call and `ChannelNewDeposit` event monitoring
- [x] Check and if needed update channel close call and `ChannelClosed` event monitoring
- [x] Check and if needed update channel settle call and `ChannelSettled` event monitoring

Part of #244

**Comment by andrevmatos** [comment]
After reading the source, a correction: the hashing of the locks is still `keccak256`, only the merkle tree was removed and the hash of the concatenated list of locks is done instead.
Sha256 is instead used for hashing the **`secret`**. A separate function (`getSecretHash`) was created to abstract this.

**Comment by andrevmatos** [comment]
Done in #294
