### ISSUE TITLE
Rollups: POC of the Light Client deployed on Arbitrum

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2904]
## Description

As Chris I want a POC of the Light Client on Arbitrum to get a better understanding of how the technology works in practice and to help determine any pitfalls and the efforts required to work around those.

## Acceptance criteria

If the outcome shows that it is feasible to deploy Raiden on Arbitrum we should have a POC that helps us get some time estimates and more details on how to make it production ready.

## Tasks
- [ ] Deploy Raiden SCs to Arbitrum testnet on Rinkeby.
- [ ] Instantiate one or more RSBs on this network, connected to an Arbitrum node.
- [ ] Transfer tokens (TTT, SVT) from L1 to L2.
- [ ] Fire up clients on it with the Arbitrum provider, explicit Matrix and PFS server.
- [ ] Document issues and optimization opportunities.
- [ ] I think Arbitrum expects gasPrice=0, and the LC at least currently enforces a minimum of 1Gwei (easy to fix).
- [ ] Check if there're any other issues on initial sync.
- [ ] Test direct and mediated transfers.
- [ ] We may not need confirmationBlocks on rollup (optimization).

If everything works fine, check on persisting these information in our deployment info, so clients would work out of the box
After this, the only pitfall I could see is the needed on-board/off-board of the rollups themselves, for which we could provide special UI/UX on Raiden clients. Other than that, it should be hopefully fully transparent.
