### ISSUE TITLE
Upgrade messages to be compatible with Alderaan clients

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#291]
## Description

After #290, we need to ensure the messages we send, receive (validate) and reply are made compatible with the current Raiden Python Client for Alderaan. This includes both adapting the existing messages formats and validation, adjusting the logic for anything that may have changed on them, and adding new messages and replies which may come and be part of the protocol, even if we don't support the feature yet.

Part of #244 

## Acceptance criteria
- the SDK is able to send direct (non-mediated transfers) to a connected partner/neighbor/hub
- mediated transfers requests fails immediately
- the SDK tries to not get out-of-sync with partner even if receiving messages for non-supported features (withdraw)
- All tests should pass
- Work is done on `next` branch

## Tasks
- [x] Adapt messages to current specification (e.g. route included in a LockedTransfer)
- [x] Fails immediately if transfer request target isn't recipient
- [x] In case there're multiple channels, prioritize direct route
- [x] Add withdraw messages schemas and validation
- [x] ~~Check (and implement, if possible) if we can just reply withdraw requests with `Processed` (to avoid getting spammed by the retries), and let it expire (like we do for receiving transfers)~~ **Withdraw requests:** Implement handling of `WithdrawRequest`, sends `WithdrawConfirmation`; reply `WithdrawExpiration` with `Processed` (as it may not be required, see https://github.com/raiden-network/raiden/issues/4721), listen to `ChannelWithdraw` events and store it in `ChannelEnd` (done in #304)

**Comment by andrevmatos** [comment]
Done in #295 and #304
