### ISSUE TITLE
dApp: Implement interfaces for Arbitrum interactions

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2983]
@taleldayekh confirm how much effort/resources should be allocated to the UI work.

### Tasks

Split if needed.

Implement interfaces for:
- [ ] Onboarding and off-boarding users from L2.
- [ ] Depositing ETH.
- [ ] Bridging tokens from L1 to L2.
- [ ] Withdrawing.
- [ ] See if any new design or design adjustments are needed for the above mentioned feature, if so, create separate issues.

Alternatively provide user with links to external sources where the above actions can be performed.

**Comment by weilbith** [comment]
After some discussions with Andre and Talel we have come to a conclusion:
The tasks specified in this issue are not specific to the new Arbitrum deployment. This is a different problem related to how users get funds in the Ethereum ecospace. This is an old problem that exists on any chain Raiden got already deployed and will potentially be deployed in future. Disregarding any argumentation if the dApp should support the user in this tasks it is is not required for the Arbitrum adaptions. It works as is without further additions excepts those to the contracts, SDK and services.

The only change that is necessary are the confirmation blocks on the notification cards. We need to check how this needs to be adapted. We will check that in a new issue.
