### ISSUE TITLE
Open channel with default parameters

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#3]
## User Story

As Chris, I want to open a channel so that I can see that the interaction with the Raiden contracts is working

## Acceptance criteria

- I can see the created channel on the explorer page
- I can do this on a testnet
- It can be done using the "production" environment and WETH
- A hardcoded address (node) is fine
- The hub does not need to be online
- I can see a success message in the Wallet

## Tasks
- [x] Setting up Web3
- [x] Configuration for the Wallet
- [x] Initial Redux set up and tests
- [x] Configure and use [Vuetify](https://vuetifyjs.com/en/)
- [x] Pull contract.json from the Raiden repo
- [x] Implement Open Channel in the Wallet
- [x] Implement Open Channel in the state 
- [x] Implement the Open Channel API method
- [x] Implement Jest tests
- [x] Implement Ganache tests
- [x] Integrate the Open Channel Method in the Wallet
- [x] Implement validations and test it
- [x] Create short instructions on how to test it

## Story Points
8
