### ISSUE TITLE
Add missing CLI endpoints for webUI, download and serve it from CLI web --web-ui parameter

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#3123]
## Description
LC CLI provides almost all endpoints from PC in a schema-compatible manner. Only a few config endpoints missing, which after implemented, should allow CLI to be a drop-in replacement for [Raiden webUI](https://github.com/raiden-network/webui), a nice user interface and admin panel for a raiden REST API-compatible client. Additionally, `--web-ui`/`--no-web-ui` command line options should control serving a pre-built version of the webUI in the respective endpoints.

This should give CLI users a better perspective of current node's state in a more ergonomic way than raw REST requests.

## Acceptance criteria
- Users can use the webUI with the CLI
- There's an easy way to serve the webUI from a CLI node

## Tasks
- [ ] Identify [possibly undocumented] endpoints needed by webUI
- [ ] Implement those endpoints with compatible schema
- [ ] Add build step/script to download and uncompress webUI
- [ ] Implement `--web-ui` to allow serving webUI files from `/`
