### ISSUE TITLE
Refactor contracts usage in the SDK

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#324]
## Description

This is a wishlist of small refactorings which would make it clearer how the SDK interacts with the contracts, clear the types and improve performance and readability

## Tasks
- [x] `src/types::RaidenContracts` is used only as the type of a cache for the contracts (registry, token, token network). Get rid of it and the private methods for creating these contracts instances and use memoized functions instead, for clarity and performance.
- [x] `src/types::TokenInfo` is used internally only for the token information cache as well. Get rid of it, use a memoized function member. 
- [x] `getPresences$` observable is actually the same for a given `action$` observable, but calling it on each epic actually create separate/equal mappings for the presences. Use a memoized function which returns a shared observable.
- [x] action `tokenMonitored` `first: boolean` member should be replaced by a `fromBlock?: number` of which block the TokenNetwork was deployed, so we scan only from that point instead of since registry deployment. This also makes it consistent with `channelMonitored`.
- [x] Move `raiden-ts/contracts` to `raiden-ts/src/contracts`, for consistency with `abi` and `deployment`, and scoped access (avoid `..` importing things relativety outside `src`). `tsc` [won't copy the contracts interfaces to outDir](https://stackoverflow.com/questions/56018167/typescript-does-not-copy-d-ts-files-to-build), so a postbuild script will be needed.
- [x] Add `chainId` and `registry` address to state, and validate it, to prevent one passing state from other networks to Raiden. It'll be more relevant when we allow one to download and re-upload a database (state, JSON).

**Comment by andrevmatos** [comment]
Done in #325 in `next`
