### ISSUE TITLE
SDK Configuration

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#326]
## Description

As part of #245, we need to provide a way to pass settings/configuration parameters to the SDK, dynamically.This config object must be made **reactive** to the SDK internals, and where it makes sense, the reactive/up-to-date values should be used and changes on it reflected immediately at runtime, with public methods to updating it. It should be optional, and sane defaults choosen for any missing fields. It should be serializable/validated through `io-ts` codecs. We should put any relevant internal parameter or constants as properties on it, and document them.

## Acceptance criteria
- There's an exposed `RaidenConfig` **codec** and its **type**.
- Raiden's create/constructor creates a default config, but accepts a `Partial<RaidenConfig>` to overwrite fields/members/params on it.
- There's some public method able to receive again a `Partial<RaidenConfig>` and re-set some parameters on the config. We should try to honor these runtime changes whenever possible/makes sense.
- Not all params may always be changeable at runtime through this method (e.g. setting a matrix server after matrix is already running has no effect, as it was already used, we don't need to reconstruct/re-login on matrix to apply this setting), but we need to document well which parameters only make sense at startup, and which one are dynamic and applied at runtime.
- This config (in itself) is NOT saved on state, but some parts or derived data from it may.
- We have good documentation on each param, where it's used, and what it does.
- We keep test coverage over these config facilities.

## Tasks
- [ ] `src/config.ts` module with `RaidenConfig` codec and type
  - [ ] RaidenConfig params which have default values should be required in the type, and the ones which may be undefined, optional.
- [ ] On startup, a default RaidenConfig, with default parameters should be constructed, and then a partial config param is accepted as parameters to (shallow) overwrite any param in the default.
- [ ] This config then goes to a `BehaviorSubject`, which is passed to `RaidenEpicDeps` as `config$: Observable<RaidenConfig>`, and epics and any other code should use this reactive object to access the config params.
- [ ] A `Raiden.config(config: Partial<RaidenConfig>)` method accepts a new partial config object, merge it with the current config and then `next` it to the BehaviorSubject.
- [ ] Some suggestions (from top of the mind) of initial parameters which may go on this config:
  - matrix server (startup)
  - matrix known servers url (startup, used only if matrixServer wasn't provided, to provide a url from where to fetch a yaml list of potential servers to choose)
  - default reveal timeout
  - default settle timeout
  - messages retry delay/backoff strategy

## Investigate
Is it worth to have `ContractsInfo` passed as a parameter in this config, instead of a independent param? Could be one less parameter to `create`, although it isn't dynamic at all, and validation against state needs to be done to throw an error if one tries to change it from what the state was created with.

Related: #237
