### ISSUE TITLE
Making the Readme nice

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#34]
## User Story

As Kelsos I want to find everything I need to start developing in a beautiful readme

## Acceptance criteria
- "Find everything" is defined
- Looks very good compared to other examples in the market
- Well structured - can be scanned very well and it [does not make me think ;-)](http://www.sensible.com/dmmt.html)
- Badges are included (CI, Coverage, Stats)

## Tasks
- [x] Find good examples, templates and decide which components to use
- [x] Define the structure of the readme
- [x] Create or pick first visual (Raiden Logo) for the Readme
- [x] Decide where to put the architecture description (#31)
- [x] Fill 'Learning about Raiden' -> @christianbrb 
- [x] Fill 'Prerequisites' -> @andrevmatos 
- [x] Fill 'Installation' - can be merged with prerequisites? -> @andrevmatos 
- [x] Fill 'Example Wallet' -> @kelsos 
- [x] Adapt 'Contributing' -> copy link to Raiden? -> @kelsos 
- [x] Fill structure (...add additional tasks ...)

## Story Points

5

## Nice Examples
- [Sojourn](https://github.com/ConsenSys/web3studio-sojourn/blob/master/README.md)
- [IPFS](https://github.com/ipfs/ipfs) - Very extensive
- [Size Limit](https://github.com/ai/size-limit)

## Template
- https://github.com/othneildrew/Best-README-Template

## More information
- [A curated list of awesome readmes](https://github.com/matiassingers/awesome-readme)
