### ISSUE TITLE
Integration tests with the Raiden client and services

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#348]
## Description
We have got a very good test coverage at the moment, but the Raiden client could break compatibility at any time. As a retro action item we wanted to discuss a way how to do integration tests.

**Requires a lot of setup. Perhaps save it for a later time since we are splitting from the Raiden develop branch at the moment.**

## Acceptance criteria
- Initially for the SDK
- That we are compatible with the Python client

## Tasks
- [ ] Lool into Python client test code
- [ ] Get cli merged to master (error handling needs some work, features need to be exposed)
- [ ] Check, if the core / python test set-up could be used (Private chain, matrix, raiden node)

**Comment by christianbrb** [comment]
Discussion in the Refinement
- Basic set-up for an automated integration test
- More like the scenario player
- With a UI framework

**Comment by christianbrb** [comment]
We could use the script, that @andrevmatos created for the #551 (not merged to master yet).
We could use derived subkey or another ETH provider (injected key) -> see raiden-installer POC (maybe using it).

Could we use ganache? -> Would be easier?

Not using the scenario player right now.

**Comment by andrevmatos** [comment]
@christianbrb The script at `cli` branch, being a node.js implementation, already uses ethers' `Wallet`, the same as a derived subkey, so it isn't needed, and can be used directly.
I don't think ganache is needed, as integration tests already setup a private geth network, which can be used directly by both light and full client, as well as the test `synapse` instance.

**Comment by kelsos** [comment]
Closing since the PR has been merged, any work related to the docker image will be done in the followup PRs
