### ISSUE TITLE
Basic design for the wallet (Open Channel) - Design implementation of iteration 2

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#35]
## Description

In today's retro, we have decided, that it makes sense to start with a professional visual design now. We want to implement and develop the design in iterations.

This issue is reserved to design, what has been implemented in iteration 2

## Acceptance criteria
- Can be implemented by @kelsos 
- The open channel screen is updated in the wallet
- It is already nicer than before (skateboard)
- Focus is on the structure
- No finetuning of the details right now
- @roy-castrillo is onboarded
- **Just open channel**

## Tasks
- [x] Meeting in Berlin
- [x] Getting access to the wallet @roy-castrillo 
- [x] Finish reading the book @roy-castrillo 
- [x] Doing the research @roy-castrillo 
- [x] Create wireframes
- [x] Implement iterations
- [x] Provide the layouts to @kelsos 
- [x] Implement design changes
- [x] Look at [Vuetify ](https://vuetifyjs.com/en/)
- [ ] Conduct tests with people
- [ ] Analyzing the results of the tests
- [ ] Finetuning
- [ ] Run tests on the implemented changes (between @kelsos and @roy-castrillo) 

## Story Points
8
