### ISSUE TITLE
Deploy Wallet to github pages continiously

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#39]
## Description

Deploy wallet to github pages at the end of the CI continuously, that it can be directly tested.

## Acceptance criteria
- Deployed to github pages

## Tasks
- [x] Research
- [x] Add script to deploy
- [x] Add master only flow to automatically deploy
- [x] Get a subdomain for the GitHub pages

## Story Points
0
