### ISSUE TITLE
Persist config in state

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#399]
## Description

This is a small architecture change for the SDK config & state. Config is persisted and restored alongside state, so we can avoid changing some config values (e.g. chosen PFS servers) between runs/sessions.
This is needed for #253, so user can check if `pfs` is undefined, and if so, proceed to chose, set and have one persisted in config/state for next runs.

## Tasks
- [x] add a `config: RaideConfig` property to `RaidenState`, which then becomes the single source of truth for the config, ensuring it's persisted as well.
- [x] A default/new config is only created when creating a default state as well.
- [x] `deps.config$` becomes wired to `deps.state$` with `pluck('config')` & `distinctUntilChanged`, as all internal uses already assume an observable which emits immediately its last value when subscribed, so no next on it.
- [x] A `raidenConfigUpdate(Partial<RaidenConfig>)` action pushes config changes to top-level properties to the reducer, to change/store/update the config inside redux.
- [x] readonly config property is exposed directly from `store.state` in the public interface (getter).
