### ISSUE TITLE
Review of Readme from comms

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#43]
## Description

Readme has been made nice #34 (see issues for example readmes)
Still needs a review from comms

## Acceptance criteria
- Readme can be released

## Tasks
- [x] Copy our "final" Readme to a google doc
- [x] Review by @franzihei 
- [x] Make requested changes

## Story Points
2
