### ISSUE TITLE
Create contributing guidelines

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#46]
## Description

Adding a `contributing.md` file which follows good practices.

## Acceptance criteria
- Require tests
- All tests past
- Coverage should not decrease
- Pick an issue and let us know

## Tasks
- [x] Use [Raiden's Contributing Guide](https://github.com/raiden-network/raiden/blob/master/CONTRIBUTING.md) as a base 
- [x] Remove any irrelevant parts 
- [x] Request Review from @andrevmatos 

## Story Points
2
