### ISSUE TITLE
I want to know what I am signing with MetaMask

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#49]
## User Story
As Chris I want to know what I am signing with MetaMask so that I am able to trust the wallet.

Closely related to #50 

## Acceptance criteria
- I see the name of the step in the progress bar
- I see a nice description for each step
- I see an indicator, that the steps in the progress bar are the messages I am signing with Metamask

## Tasks
- [x] Create wireframes
- [x] Design prototypes in sketch
- [x] Copy text for the description and the steps
- [ ] Implement everything in the wallet

## Story Points
2
