### ISSUE TITLE
I want to get feedback on the channel open progress

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#50]
## User Story
As Chris, I want to get feedback on the channel open progress so that I don't close or reload the window because it takes so long.

## Acceptance criteria
- I see the steps upfront
- I am getting informed, that I have got accept the transaction in Metamask
- I see which step has been completed (mined successfully)
- I can see how many block have been passed since the transaction has been submitted

## Tasks
- [ ] Copy text needs to be written
- [ ] Create wireframes
- [ ] Send intermediary events from the SDK
- [ ] Implement everything on the wallet (taking the design, the wireframes and the changes in the SDK)

## Story Points
3
