### ISSUE TITLE
Finetuning of the payment flow

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#642]
## Description
The payment flow looks great 😄 👍 

Some small finetuning:
- [x] Instead of `SVT Balance` write `SVT Balance to pay the Pathfinding Service`
- [x] Button on hover `Mint SVT and Deposit to the User Deposit Contract to pay for PFS requests`
- [x] Header in table `PFS `-> `Pathfinding Service`
- [x] `pfs-goerli-with-fee.services-test` to `Route(s) provided by pfs-goerli-with-fee.services-test with the number of hops and the estimated fee`
- [x] Price in TTT (not SVT) in table -> fixed via #610 
- [x] `Confirm `to `Confirm to pay a mediation fee of ... TTT`
- [x] ~~Total Amount~~ ->  Is already an issue @nephix #543 
- [x] Show `Send Successful` screen longer

-> Proposed solutions still open for discussions

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by kelsos** [comment]
@christianbrb we still need to discuss and improve a number of cases.

**Comment by nephix** [comment]
> Total Amount -> I think there is already an issue @nephix

@christianbrb it's https://github.com/raiden-network/light-client/issues/543

**Comment by nephix** [comment]
> Price in TTT (not SVT) in table

Seems to be https://github.com/raiden-network/light-client/issues/610

**Comment by andrevmatos** [comment]
Another: - upon automatic cases (free single PFS, free single route, direct transfer), still show the confirmation screen with all information before actually starting the payment
About `SVT Balance to pay the Pathfinding Service`, may take into account this token will be used in the future for MS as well.
