### ISSUE TITLE
Reduce complexity on raiden-ts/src/raiden.ts

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#657]
## Description

According to the code climate reports [raiden-ts/src/raiden.ts](https://github.com/raiden-network/light-client/blob/master/raiden-ts/src/raiden.ts) is one of the often modified classes that has a high maintenance cost due to complexity. 

The purpose of this issue is to identify the possible improvements that can be done on raiden.ts in order to reduce the complexity and improve the maintainability of the class.

## Acceptance criteria
- 

## Tasks
- [x] Split Observable mappings out of the constructor 
- [x] Single line declarations + linting
- [x] Split small functions out of create factory
- [x] Writing new tests
