### ISSUE TITLE
Reduce complexity on raiden-ts/src/transfers/epics.ts

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#659]
## Description

According to the code climate reports [raiden-ts/src/transfers/epics.ts](https://github.com/raiden-network/light-client/blob/master/raiden-ts/src/transfers/epics.ts) is one of the often modified classes that has a high maintenance cost due to complexity.

The purpose of this issue is to identify the possible improvements that can be done on raiden.ts in order to reduce the complexity and improve the maintainability of the class.

## Acceptance criteria
- 

## Tasks
- [x] Reduce nesting on MakeAndSignUnlock
- [x] Reduce nesting on MakeAndSignLockExpired
- [x] Reduce nesting on MakeAndSignWithdrawConfirmation
- [x] Reduce nesting on TransferSignedRetryMessageEpic
     - [x] Research, if nesting in PublishReplay can be reduced
- [x] Check if state$.pipe(publishReplay(....$.pipe( can become a utility function
- [x] Split out promise like observable utility function
- [ ] Checking the validity of messages in a function
- [x] Check, if the message is the same
- [x] Switch statement in TransferAndGenerateSignEnvelopeMessageEpic
- [x] Check, if Asserts can be used
- [ ] Adjust the duplication threshold (a little bit up)
- [x] Adjust tests
