### ISSUE TITLE
Decide on sensible thresholds for CodeClimate

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#661]
## Description

As we discussed the CodeClimate defaults seem too low. As we go through the refactoring issues we should decide on some reasonable thresholds in order to configure CodeClimate.

## Acceptance criteria
- 

## Tasks
- [ ] Change CodeClimate to the following constants -> as a target (not enforcing it)
    - [ ] 500 lines per file
    - [ ] 50 lines per function

**Comment by christianbrb** [comment]
This has been done :) See #755
