### ISSUE TITLE
Finetuning of transfer stepper in case of errors and steps skipped

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#695]
## Description
The whole transfer stepper does not work in all edge cases. We need to implement a proper error handling from a user perspective and decide what do show, if steps are skipped.

## Acceptance criteria
- Inform the user when PFS is not used (single route)
- If there are more than one route we might want to let the user choose a more reliable route even if it is more expensive
- Look at the already existing issue for error messages #693 

## Tasks
- [x] If we find a single route don't ask confirmation
- [ ] Make the stepper properly report if any error happens during the steps
- [x] Add skip icon to the current stepper

**Comment by christianbrb** [comment]
We need to check if this is still the case
