### ISSUE TITLE
Upgrade wiki "Using the SDK in a private chain or a development environment" to Alderaan

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#750]
## Description
The wiki page "[Using the SDK in a private chain or a development environment](https://github.com/raiden-network/light-client/wiki/Using-the-SDK-in-a-private-chain-or-a-development-environment)" still points to Red Eyes. It needs to be upgraded to Alderaan.

## Acceptance criteria
- The user should know how to deploy the contracts and run Light Client on a private compatible chain.

## Tasks
- Set up a private environment where everything runs locally
- Go through the whole stack and see what works

**Comment by kelsos** [comment]
@christianbrb also maybe instead of the Wiki it would make more sense to include it in the docs?

**Comment by christianbrb** [comment]
I think it still needs some finetuning:
- [ ] Removing the private chain guide from the wiki
- [ ] Removing the following paragraph from the docs (https://lightclient.raiden.network/docs/connecting/#using-the-sdk-in-a-private-chain-or-a-development-environment)
- [ ] Adding the private chain guide to the docs (I don't find it)

**Comment by kelsos** [comment]
@christianbrb I just removed it from the wiki but the part about it not being in the docs. If that is the last thing we merged that's the reason it's not there. I had a [skip ci] flag so it probably didn't fire the CI after getting merged. As soon as we merge another commit though things should be fine.

**Comment by christianbrb** [comment]
Ok, great :) I am patient ☺️

**Comment by kelsos** [comment]
after the last build the guide is live :D https://lightclient.raiden.network/docs/private-chain/

**Comment by christianbrb** [comment]
Great :)
