### ISSUE TITLE
Reviewing and deciding on PR guidelines

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#758]
## Description
@nephix had very good remarks on our PR process in #753 
As a follow up we need to clarify the comments within the PR:
- [x] https://github.com/raiden-network/light-client/pull/753#pullrequestreview-333204053
- [x] https://github.com/raiden-network/light-client/pull/753#pullrequestreview-333204244
- [x] https://github.com/raiden-network/light-client/pull/753#pullrequestreview-333204681
- [x] https://github.com/raiden-network/light-client/pull/753#pullrequestreview-333205685
- [x] https://github.com/raiden-network/light-client/pull/753#pullrequestreview-333400955

@kelsos @andrevmatos @taleldayekh Anything to add?

## Acceptance criteria
- Relevant and updated content

## Tasks
- [ ] Schedule call to discuss on the points above
- [ ] Update the MD file

**Comment by nephix** [comment]
* Comment when starting to review: Remove
* Contribute to other people's PRs: Keep, mention to inform owner
* Break up pull requests into smaller ones: Keep
* Draft/Ready for review pull requests: Keep
* Kebab cased component names: Will be removed, already an eslint rule
