### ISSUE TITLE
Reviewing and cleaning up the new and old docs

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#778]
## Description
The new docs look great :)
There are some minor issues within the docs and duplication in the the old docs, which need to be found and cleaned up.

## Acceptance criteria
- 

## Tasks
- [x] [Prerequisites](https://github.com/raiden-network/light-client#prerequisites) are missing
- [x] [Installing the dApp](https://github.com/raiden-network/light-client#dapp-installation) is missing
- [ ] Using ;) active voice (eg. Install the SDK instead of Installing the SDK)
- [x] Structure and shorten [this section](https://lightclient.raiden.network/docs/installing/)
- [x] Remove SDK usage from main readme (PR #787)

**Comment by taleldayekh** [comment]
I created a new issue #850 for tackling general improvements when it comes to the content structure and tone of voice.

**Comment by taleldayekh** [comment]
Since all boxes except one have been ticked and I've created a new issue for the docs content I will close this issue now.
