### ISSUE TITLE
Refactor epics tests fixtures for action$, state$ and latest$

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#871]
## Description

Currently, our epics tests fixtures are each one done in its own way. Some with action/state passed with `of`, some with `Subject/BehaviorSubject` constructed in place, some with it done per suite.

We need to standardize it, and also make sure they're always re-defined/initialized between tests.

## Acceptance criteria
- epics tests are standardized, and can use `latest$` properly
- fixtures and mocks are reset and re-initialized, for independent testing
  - this should fix one test affecting the following ones

## Tasks
- [x] `action$` is a `Subject` provided from fixture
- [x] `state$` is a `BehaviorSubject` started with initial state from fixture
- [x] `latest$` is wired from `action$` & `state$` with `getLatest$`
- [ ] They're all `complete`d `afterEach` test, and initialized `beforeEach`
- [ ] All test suites (at least unit, for now) should survive `mockReset` `afterEach`, be pristine after each, and any default mock be put again in place.

**Comment by andrevmatos** [comment]
The fixtures were implementeded. The transfers tests were converted in #1068 . Transport was done as well.

**Comment by andrevmatos** [comment]
I did the fixtures, and some tests, but the `channels.spec.ts` still needs to be finished, and someone else could do it. Nonetheless, this is releated and may be done in the scope of the tests refactoring at #1268

**Comment by kelsos** [comment]
Sure either I or Thomas can do it.

**Comment by taleldayekh** [comment]
Superseded by #1377
