### ISSUE TITLE
Having a test environment

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#928]
## Description
Having a test environment to work with https://lightclient.raiden.network/ including:
- PFS
- Matrix
- Raiden Hub

## Acceptance criteria
- A small contained test environment that we can control

## Tasks
- [x] Merge contracts update PR
- [x] Decide Raiden version
- [x] Target version on Docker
- [x] Modify dApp to connect to the new environment

**Comment by kelsos** [comment]
@christianbrb I also think that in order to ensure a stable environment we need to have two different versions deployed on that is based on the latest master and one that is deployed only when it makes sense.

**Comment by christianbrb** [comment]
Having a test environment https://lightclient.raiden.network/ 

We need:
- PFS/MS/Matrix package
- Raiden Hub
     - Ansible set-up
     - Nightly (not updated since 2 month)

**Comment by christianbrb** [comment]
@eorituz started setting up a separate [Raiden Service Bundle](https://github.com/raiden-network/raiden-service-bundle) but was running into an error.

**Comment by christianbrb** [comment]
So you have a standalone version of matrix & the services running at `pfs.raidentransport.test001.env.raiden.network` (PFS) and `raidentransport.test001.env.raiden.network` (Matrix) right now.
Please not that it is completly standalone and does not federate with the other Matrix servers (you will need to hardcode the PFS and Matrix server in all your config files)

**Comment by christianbrb** [comment]
Next step is setting up the Raiden Hub with @nlsdfnbch and setting the PFS and Matrix in the config files

**Comment by kelsos** [comment]
Other than that we need to decide on a version of Raiden-py that we will use in this environment (see if we can also have binaries. And also provide instructions on how to connect/use the test environment.

**Comment by kelsos** [comment]
A version of raiden version has been decided and has been tagged on dockerhub https://hub.docker.com/layers/raidennetwork/raiden/testenv001

**Comment by kelsos** [comment]
The last thing remaining to close this issue based on the description is the deployment of Raiden Hub and the update of the documentation to include that.

**Comment by nephix** [comment]
I attempted to build a macOS binary but it failed with the following error:
```sh
pyinstaller --noconfirm --clean raiden.spec
57 INFO: PyInstaller: 3.6
57 INFO: Python: 3.7.6
64 INFO: Platform: Darwin-19.3.0-x86_64-i386-64bit
67 INFO: UPX is not available.
67 INFO: Removing temporary files and cleaning cache in /Users/nephix/Library/Application Support/pyinstaller
[1]    11896 abort      pyinstaller --noconfirm --clean raiden.spec
```

and 
```sh
/usr/lib/libcrypto.dylib
abort() called
Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.
```

As there's no immediate need for a macOS binary, we agreed with @eorituz to not investigate this further

**Comment by kelsos** [comment]
@nephix I think @taleldayekh encountered this `libcrypto` issue before and I think he already did some workarounds to avoid this on his machine. Can you send us the instructions? Maybe we can try building it here.

**Comment by nlsdfnbch** [comment]
A Raiden Node plus Hub has been deployed and made available at http://hub.test.raiden.network (vpn required). Port `5001` exposes the raiden client's API - let me know if this is needed, or If I can shut that port for inbound traffic.

Should you require an update of the image or the hub version, there is a Tower job available to do so [here](http://tower.raiden.network/#/templates/job_template/25). Clicking the 'launch' button will open up a dialogue box where you can configure the test env.

If you like, I'll gladly give you a quick how-to session via zoom.

@kelsos / @christianbrb

**Comment by kelsos** [comment]
@nlsdfnbch thank you for the effort. I have a question. How easy would it be for us to close the 5001 port and allow the actual hub page to be accessed from the outside world?

A quick how-to would be appreciated. Let's schedule it after @christianbrb is back :)

**Comment by kelsos** [comment]
My work should be ready but I had problems deploying so we could not test it @taleldayekh can coordinate with @nlsdfnbch on Monday to verify that this is deployed and to verify that it works.

If any major issues remaining on Monday, in case I don't have enough time @andrevmatos  could have a look and provide assistance or any fixes needed.

**Comment by kelsos** [comment]
@christianbrb we should probably include the hub and it's ens domain to the readme maybe. I need to do only a few changes, e.g. change to `TTT` now that the workshop is done.
