### ISSUE TITLE
Don't expire lock whose secret got registered on-chain

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#986]
## Description

On Raiden protocol, if for any reason a secret gets registered on-chain before lock timeout, instead of being unlocked, we must not expire the lock as it won't get accepted by partner. We may unlock, if requested, but either way, the transfer should be considered complete and successful. On-chain registered secrets may be unlocked on-chain **after** channel is settled.
This isn't the happiest case, but isn't an error either, and is valid per protocol. It isn't crucial for our usecases, but as it's a valid protocol path, we must comply to avoid getting out of sync with partner.

Related:
#843 : we don't have information if partner did or didn't register on-chain, but if it did, we definitely got out of sync upon expiration
#613 : we must account for confirmation blocks for threshold calculations
#786 : protocol compliance

## Acceptance criteria
- We comply with this exceptional, uncommon but possible/valid codepath

## Tasks
- [x] Monitor SecretRegistry for secrets we know about
- [x] Pending transfer whose secret gets registered must not expire, and be considered successful
- [x] We allow unlock even after expiration if secret got registered inside timeout (TBD)
